Add edit and delete event action
douglara/woofed-crm pull request #155
Opened 2023-10-18 21:26 UTC by YukioArie

2023-10-24 10:47 UTC, douglara requested changes

2023-10-24 10:47 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    ]
Esse trecho aqui talvez seja melhor colocar no model, assim se fizermos uma deleção por exemplo pelo sidekiq ou até mesmo console o elemento é removido da página.
Segue um exemplo:
https://youtu.be/xSkq9vQgT7k?si=-fY_L2QTrvmXxU5c&t=534

2023-10-24 10:47 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
>      @event.update(event_params)
Aqui da para remover esse update
```suggestion
```

2023-10-24 10:47 UTC, douglara commented on app/views/accounts/contacts/events/edit.html.erb
> +<div class="group event-<%= @event.scheduled_kind %> event-item-<%= @event.from %> my-2">
Esse edit aqui precisamos ver uma maneira dele ser dinâmico.
Por exemplo se eu criar um evento do tipo "note" ao editar ela vira do tipo "activity"
Se encontrarmos uma forma de re utilizar as partials do forms seria interessante também

2023-10-31 02:40 UTC, douglara commented
Nussaa ta ficando muito bom heimmm 😍
Só um detalhe que eu notei quando a atividade é concluída ela precisa aparecer no bloco de concluídas, bora discutir melhor.



https://github.com/douglara/woofed-crm/assets/14988496/35c3b38c-56aa-4978-bf83-50da2438cd1f

2023-10-31 22:53 UTC, douglara requested changes

2023-10-31 22:53 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +
Aqui acho que da para remover
```suggestion
```

2023-10-31 22:53 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    # end
```suggestion
```

2023-10-31 22:53 UTC, douglara commented on app/models/deal.rb
> +    events.planned.order(:due).detect { |event| event.due.present? } rescue nil
Então acho que essa correção de evento planejado poderia ser feito no método `planned` aqui seria mais pegar o próximo evento.

2023-10-31 22:53 UTC, douglara commented on app/views/components/events/_form.html.erb
> +    <div data-events-form-target="kindNote" hidden class="h-full w-full pt-3">
Fiquei na dúvida porque foi retirado do `components/events/form/note`

2023-11-06 10:54 UTC, douglara commented
Alguns pontos que eu peguei:
- Quando uma atividade é criada alguma coisa está quebrando o histórico
- Quando editamos um evento com data o valor dela não está sendo carregado na edição


https://github.com/douglara/woofed-crm/assets/14988496/9418abde-b29e-4923-a82d-1cceab5d8cfa

2023-11-07 09:56 UTC, douglara requested changes

2023-11-07 09:56 UTC, douglara commented on app/models/event.rb
> +  belongs_to :deal
Esse relacionamento já esta sendo feito na linha 38

2023-11-07 09:56 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +            <%= link_to account_contact_event_path(event.account, event.deal.contact, event), method: :delete, class: 'flex items-center space-x-2 px-4 py-2 hover:bg-gray-100 hover:text-dark-gray-pal
Essa linha esta quebrando o teste:
`spec/integration/use_cases/accounts/apps/chatwoots/webhooks/events/message/message_spec.rb:11`
Pois é possível que um contato não tenha nenhum deal.

2023-11-08 23:52 UTC, douglara commented
@YukioArie encontrei um bug, parece que ocorre só na primeira vez que edita

https://github.com/douglara/woofed-crm/assets/14988496/76e8edaa-11d4-44b3-bf5d-2fa923971417

2023-11-09 00:37 UTC, douglara requested changes

2023-11-09 00:37 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +        <% unless event.kind == 'wpp_connect_message' || event.kind == 'chatwoot_message' %>
Essa verificação acho que fica legal no model.

2023-11-09 03:54 UTC, YukioArie commented
@douglara antes de colocar em produção, verifica se está dando problema de carregamento dos icones do lucide #80, na pagina principal (o msm problema q a gnt teve antes). Pq eu fiz o merge do development, e esse está acontecendo, o q n era pra acontecer. Pode ser a minha máquina

2023-11-09 04:03 UTC, YukioArie commented
@douglara pelo q verifiquei está acontecendo até em produção o problema do lucide. N tem nd a ver com esse card

2023-11-09 22:56 UTC, douglara commented
@YukioArie aqui esta funcionando

https://github.com/douglara/woofed-crm/assets/14988496/fc580444-387c-4b82-87d3-2c467cf10390

2023-11-09 23:07 UTC, merged