Sync create contact woofed/chatwoot
douglara/woofed-crm pull request #172
Opened 2023-10-31 12:37 UTC by YukioArie

2023-10-31 23:08 UTC, douglara requested changes

2023-10-31 23:08 UTC, douglara commented on app/controllers/accounts/contacts_controller.rb
> +      Accounts::Apps::Chatwoots::Webhooks::SendContactWorker.perform_async(chatwoot_id, @contact.to_json)
Essas lógicas acho que podem serem feitas escutando as alterações do contato

2023-10-31 23:08 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +      # "identifier": "string",
```suggestion
```

2023-10-31 23:08 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +    byebug
```suggestion
```

2023-10-31 23:08 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/webhooks/events/send_contact_spec.rb
> +        result = Accounts::Apps::Chatwoots::Webhooks::SendContact.call(chatwoot, contact_data)
Acho que esse teste não esta funcionando legal

2023-10-31 23:08 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/webhooks/events/send_contact_spec.rb
> +    let(:contact_response) { { ok: 'contact created', chatwoot_id: 715 }.to_json }
A resposta do chatwoot é diferente

2023-10-31 23:08 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact_worker.rb
> +        contact = JSON.parse(contact_json)
Aqui como vai rodar em background talvez pegar o contato do banco seja mais interessante que receber via json

2023-11-29 02:59 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +    response_body = JSON.parse(request.body) rescue {}
Aqui eu removeria esse rescue para evitar de mascarar uma exception

2023-11-29 02:59 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact_worker.rb
> +
```suggestion
```

2023-11-29 02:59 UTC, douglara commented on app/controllers/accounts/contacts_controller.rb
> +      Accounts::Apps::Chatwoots::Webhooks::SendContactWorker.perform_async(chatwoot_id, @contact.to_json)
Aqui faltou adicionar o callback no model

2023-11-29 03:03 UTC, douglara requested changes

2023-11-29 03:03 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +    request = Faraday.post(
Tava pensando, talvez seja interessante antes de criar consultar se esse contato já existe no chatwoot.
Talvez transformar em um find or create

2023-11-29 03:03 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +      "email": contact['email'],
Será que se um contato estiver sem email ele é criado?

2023-11-29 05:05 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +    request = Faraday.post(
Na nossa implementação a gnt já consegue verificar esse erro. Quando a gnt cria um contato no woofed com um email já existente no chatwoot,  ele n cria no chatwoot. Esse metodo retorna uma resposta informando q o email já existe no chatwoot. 
![image](https://github.com/douglara/woofed-crm/assets/45243355/88d2b26d-9ba0-4b0a-9754-ad58c4667084)

2023-11-29 05:20 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +      "email": contact['email'],
N, ele n é criado no chatwoot.

2023-11-29 11:59 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +    request = Faraday.post(
Alinhando melhor sobre esse ponto e decidimos seguir somente com o fluxo de criação partindo da ideia que o chatwoot e o woofed estão com todos os contatos sincronizados. A sincronização vai ser discutida em outro card.

2023-11-29 12:12 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/send_contact.rb
> +      "email": contact['email'],
Sim é criado mas não aparece na busca do chatwoot.

2023-11-30 12:55 UTC, YukioArie commented
@douglara, o lance de criar contato ta funcionando aqui. Hj mais cedo n foi pq na branch que eu estava tinha arquivos que eu tinha alterado e quando eu fui mudar para essa branch ele n trocou, daí nem percebemos huahuahua.

2023-11-30 16:46 UTC, YukioArie commented
@douglara, testei novamente criando o contato no woofed e parece que ele cria uns jobs a mais por conta do que a gnt conversou mais cedo, mas ele n fica em loop infinito como imaginamos. Acredito q n irá quebrar o sistema esses jobs a mais, segue o log dos jobs quando criamos um contato no woofed: 
![image](https://github.com/douglara/woofed-crm/assets/45243355/3e64428d-1b89-4d0e-9351-084cd9538a98)

2023-12-04 20:46 UTC, douglara requested changes

2023-12-04 20:46 UTC, douglara commented on app/models/contact.rb
> +  # after_commit :export_contact_to_chatwoot, on: :update
```suggestion
```

2023-12-04 20:46 UTC, douglara commented on app/models/contact.rb
> +  # after_commit :export_contact_to_chatwoot, on: :update
Boas assim acho que fica melhor mesmo

2023-12-04 20:46 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/export_contact.rb
> +class Accounts::Apps::Chatwoots::Webhooks::ExportContact
Aqui acho que da para tirar do caminho `webhooks` a ideia desse contexto é ficar as logicas de webhooks recebidos do chatwoot.
Como essa logica é do Woofed para o Chatwoot talvez alguns nomes:
```
Accounts::Apps::Chatwoots::ExportContact
Accounts::Apps::Chatwoots::SyncContactFromWoofed
Accounts::Apps::Chatwoots::SyncContact
Accounts::Apps::Chatwoots::SendContact
Accounts::Apps::Chatwoots::SendContactToChatwoot
```

2023-12-04 20:46 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/export_contact.spec.rb
> +      result = Accounts::Apps::Chatwoots::Webhooks::ExportContact.call(chatwoot, contact)
Então nesse caso aqui imagino que precisa atualizar o contato da para criar um expect para ver se isso ocorreu.

2023-12-04 23:11 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/export_contact.rb
> +class Accounts::Apps::Chatwoots::Webhooks::ExportContact
Acho q Accounts::Apps::Chatwoots::ExportContact é o mais interessante, só esse trecho da para entender qual é a função dessa classe. Fora que os outros nomes existem uma redundância como por exemplo Accounts::Apps::Chatwoots::SendContactToChatwoot

2023-12-06 10:56 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/search_contact_spec.rb
> +          .to_return(body: {error: "Contact not found"}.to_json, status: 200, headers: { 'Content-Type' => 'application/json' })
Aqui o stub correto é o:
`{"meta":{"count":0,"current_page":"1"},"payload":[]}`

2023-12-06 10:58 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/export_contact.spec.rb
> +require 'rails_helper'
Esse aquivo esta com o nome incorreto hehe, precisa ser:
`chatwoots/export_contact_spec.rb`

2023-12-06 12:26 UTC, merged