Fix and improves contact phone number field
douglara/woofed-crm pull request #194
Opened 2023-11-10 06:10 UTC by YukioArie

2023-11-14 21:33 UTC, YukioArie commented
@douglara, o erro de teste nessa branch é que quando faz o request "#{wpp_connect.endpoint_url}/api/#{wpp_connect.session}/all-groups" para pegar o contato, ele retorna esse número de telefone: 120363101980547250. O problema é que na validação que a gnt fez ele tem um limite de 16 caracteres, fora que precisa ter o + no inicio dos numeros. Para solucionar esse problema, a gnt pode aumentar o numero de caracteres na validação, e quando criar o contato pelo request do wpp connect, colocaremos o + no inicio do numero do telefone, mas n sei se essa solucão é o certo a se fazer. O erro é no arquivo app/use_cases/accounts/apps/wpp_connects/sync/group.rb:21

2023-11-27 01:51 UTC, douglara requested changes

2023-11-27 01:51 UTC, douglara commented on app/javascript/controllers/input_mask_controller.js
> +            console.log(fieldName)
Aqui da para remover esse console

2023-11-27 01:51 UTC, douglara commented on app/javascript/controllers/input_mask_controller.js
> +            if (fieldName === 'contactphone') {
Hmmm não sei esse formato, eu optaria em colocar especifico para cada caso em vez de um controller que tenta colocar várias mascaras acho que deixa muita responsabilidade diversa em uma coisa só

2023-11-27 01:51 UTC, douglara commented on app/views/accounts/contacts/_form.html.erb
> +<%= form_for([current_user.account, contact], html:{class: "flex flex-col gap-5"}, data:{ controller:"input-mask" } ) do | form | %>
Aqui talvez de pra colocar o controller stimulus somente no input que for utilizar

2023-11-27 01:51 UTC, douglara commented on app/views/accounts/deals/details/_show_custom_attributes.html.erb
> +  <% if custom_attribute[1].present? %>
Porque precisa desse if aqui?

2023-11-27 01:51 UTC, douglara commented on app/views/accounts/settings/custom_attributes_definitions/_form.html.erb
> +      <%= form.text_field :attribute_display_name, placeholder: "CPF", class: 'form-input' %>
Acho que o placeholder "Campo 1" fica um pouco melhor nesse caso, como é um campo dinâmico que pode ser qualquer coisa.

2023-11-27 01:51 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +    it "create a new contact" do
Essa descrição esta incorreta

2023-11-27 01:51 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +        before do
A Indentação desse arquivo ta com problema

2023-11-27 01:51 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +                end.to change(Contact, :count).by(0)
Aqui faltou verificar o motivo do erro

2023-11-27 02:03 UTC, douglara commented
> @douglara, o erro de teste nessa branch é que quando faz o request "#{wpp_connect.endpoint_url}/api/#{wpp_connect.session}/all-groups" para pegar o contato, ele retorna esse número de telefone: 120363101980547250. O problema é que na validação que a gnt fez ele tem um limite de 16 caracteres, fora que precisa ter o + no inicio dos numeros. Para solucionar esse problema, a gnt pode aumentar o numero de caracteres na validação, e quando criar o contato pelo request do wpp connect, colocaremos o + no inicio do numero do telefone, mas n sei se essa solucão é o certo a se fazer. O erro é no arquivo app/use_cases/accounts/apps/wpp_connects/sync/group.rb:21

Boaa tem pontuado, fiz o ajuste para importar os contatos do wpp com o `+` e retirei para os grupos importar como telefone assim resolve esses problemas sem ficar inconsistente

2023-11-29 03:13 UTC, douglara requested changes

2023-11-29 03:13 UTC, douglara commented on app/views/accounts/deals/details/_edit.html.erb
> +  <%= form_with(model: model, url: update_path, data:{controller: "input-mask"}) do |form| %>
Esse aqui acho que faltou tirar né?

2023-12-10 01:43 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +  context 'GET #new' do
Aqui seria a listagem de contatos o #index

2023-12-10 01:43 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +    it 'create a new contact' do
So ajustes de nome

2023-12-10 01:43 UTC, douglara commented on spec/controllers/accounts/contacts_controller_spec.rb
> +    context 'not create a new contact' do
Os testes ficaram topss heim

2023-12-10 01:52 UTC, merged