Add pipeline filter: lost/won deals. (reload html)
douglara/woofed-crm pull request #211
Opened 2023-11-27 12:27 UTC by YukioArie

@douglara essa versão ele carrega o html todo e renderiza somente o turbo frame. Ref (#187)

2024-01-15 10:58 UTC, douglara reviewed
Aqui seria complicado fechar o filtro depois de selecionar uma opção?

https://github.com/douglara/woofed-crm/assets/14988496/89afeeae-81be-4564-9c01-e2d057b74ffa

2024-01-16 13:12 UTC, YukioArie commented
https://github.com/themesberg/flowbite/discussions/184
https://stackoverflow.com/questions/77491491/close-the-flowbite-navbar-dropdown-on-click-of-one-of-the-links

2024-01-16 22:39 UTC, YukioArie commented
@douglara, consegui fazer fechar o filtro logo após selecionar uma opção 🚀

2024-01-17 09:29 UTC, douglara requested changes
Ficou topss boa!

2024-01-17 09:29 UTC, douglara commented on app/views/layouts/shared/_navbar_pipe.html.erb
> +            <% end %> -->
Só remover esse comentários aqui

2024-01-18 10:51 UTC, merged