Add import contacts POC
douglara/woofed-crm pull request #213
Opened 2023-12-01 06:24 UTC by YukioArie

2023-12-04 19:25 UTC, douglara requested changes

2023-12-04 19:25 UTC, douglara commented on app/controllers/accounts/pipelines_controller.rb
> +    @stage = Stage.find(params[:stage_id])
Aqui acho que é legal colocar aquele current_user.account.stages.find()
Para evitar de subir em alguma que usuário não tenha acesso

2023-12-04 19:25 UTC, douglara commented on app/javascript/controllers/change_request_to_turbo_stream_controller.js
> +
```suggestion
```

2023-12-04 19:38 UTC, YukioArie commented on app/controllers/accounts/pipelines_controller.rb
> +    @stage = Stage.find(params[:stage_id])
Vc tem razão! Acabei de ajustar.

2023-12-06 20:55 UTC, douglara commented
Verificar validação de formatação do telefone com o +

2023-12-11 00:22 UTC, merged