Events migrations
douglara/woofed-crm pull request #215
Opened 2023-12-06 23:04 UTC by YukioArie

![Uploading image.png…]()

2023-12-19 10:52 UTC, douglara requested changes

2023-12-19 10:52 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    @event.scheduled_at = Time.now if params['event']['send_now'] == 'true'
Bora colocar isso aqui no event builder, ai da para re aproveitar para a API

2023-12-19 10:52 UTC, douglara commented on app/models/event.rb
> +  after_update :broadcast_done_at_update, if: -> { saved_change_to_done_at? }
Hmmm tantos callbacks e regras de if começa a complicar entender isso

2023-12-19 10:52 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/messages/delivery_job.rb
> +    if !event.done? && (event.scheduled_at - Time.current.in_time_zone).abs <= 30.seconds
Aqui precisamos testar em situações diversas

2023-12-19 10:52 UTC, douglara commented on app/views/accounts/contacts/events/_events.html.erb
> +            <%= render partial: 'accounts/contacts/events/events_planned', locals: {deal: @deal}%>
Aqui da para rever os nomes das partials

2023-12-19 10:52 UTC, douglara commented on spec/controllers/accounts/contacts/events_controller.spec.rb
> +            params = valid_params.deep_merge(event: { kind: 'note', done: '1' })
Acho que esse done: true para o note seria melhor colocar no event builder para evitar de ser possível alterar no frontend e também ficar simples na API

2023-12-19 10:52 UTC, douglara commented on spec/controllers/accounts/contacts/events_controller.spec.rb
> +            expect(Event.first.done?).to eq(true)
Hmmm done no caso do chatwoot não é preenchido pelo worker que envia a mensagem?

2023-12-19 11:04 UTC, YukioArie commented on spec/controllers/accounts/contacts/events_controller.spec.rb
> +            expect(Event.first.done?).to eq(true)
Isso, é q nesse caso eu n estou testando com o sidekiq :(

2024-01-06 21:57 UTC, douglara requested changes
@YukioArie tem bastante testes quebrando

2024-01-15 10:38 UTC, douglara requested changes
Tem alguma coisa esquisita na construção do objeto do event, ele já esta sendo iniciado como done_at preenchido.
Isso pode ser ruim para o caso do cliente abrir a página do evento e criar o evento horas depois, a data de done vai ficar com o do momento que ele carregou a página pela primeira vez.

![image](https://github.com/douglara/woofed-crm/assets/14988496/c8120d67-6490-4634-979b-301ab6addac1)

2024-01-15 10:38 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
>      @event.from_me = true
Vamos rever esse from_me em outro card.

2024-01-15 10:38 UTC, douglara commented on app/models/concerns/deal/broadcastable.rb
> +        broadcast_prepend_to [contact_id, 'events'],
Aqui é melhor utilizar o `broadcast_prepend_later_to` para processar a partial em background
https://www.rubydoc.info/gems/turbo-rails/0.5.2/Turbo/Broadcastable#broadcast_prepend_later_to-instance_method

2024-01-15 10:38 UTC, douglara commented on app/models/concerns/deal/broadcastable.rb
> +        broadcast_replace_to [contact_id, 'events'],
Aqui `broadcast_replace_later`

2024-01-15 10:38 UTC, douglara commented on app/models/concerns/event/decorators.rb
> +    distance_of_time_in_words(self.scheduled_at - Time.current).sub('aproximadamente', '').strip rescue ''
Hmmm aqui talvez vale a pena deixar a exception ocorrer ai corrigimos nos lugares que não deveria estar chamando

2024-01-15 10:38 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/messages/delivery_job.rb
> +  def check_scheduled_at(event)
Hmmm aqui talvez um nome que explica melhor o que esse método faz, talvez `should_delivery?`?
Ai da pra colocar o event.done? dentro

2024-01-15 10:38 UTC, douglara commented on spec/controllers/accounts/contacts/events_controller_spec.rb
> +            expect(Event.first.kind).to eq(params[:event][:kind])
Aqui da pra trocar para o `event_created` e tem outros lugares nesse teste também

2024-01-16 04:48 UTC, YukioArie commented on app/models/concerns/deal/broadcastable.rb
> +        broadcast_prepend_to [contact_id, 'events'],
Boa, bem lembrado! 🚀

2024-01-16 04:52 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/messages/delivery_job.rb
> +  def check_scheduled_at(event)
Boa ideia!

2024-01-16 19:04 UTC, YukioArie commented on app/controllers/accounts/contacts/events_controller.rb
>      @event.from_me = true
Beleza

2024-01-16 19:05 UTC, YukioArie commented on app/models/concerns/event/decorators.rb
> +    distance_of_time_in_words(self.scheduled_at - Time.current).sub('aproximadamente', '').strip rescue ''
Boa!

2024-01-16 19:06 UTC, YukioArie commented on app/models/concerns/deal/broadcastable.rb
> +        broadcast_replace_to [contact_id, 'events'],
Feito!

2024-01-17 10:12 UTC, douglara requested changes

2024-01-17 10:12 UTC, douglara commented on app/models/deal.rb
>    end
Hmmm isso aqui ta meio esquisito o método se chama `next_event_scheduled` mas puxa do `events.planned` acho que pode gera confusão no futuro, bora conversarmos melhor.

2024-01-17 10:12 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +        <% unless (event.kind == "chatwoot_message" || event.kind == "wpp_connect_message") && event.done? %>
Aqui acho que é mais interessante atualizar a regra no método `editable?` para ela não ficar espalhada entre o model e a view

2024-01-17 10:12 UTC, douglara commented on app/views/accounts/contacts/events/_events.html.erb
> +          <%= turbo_frame_tag "events_to_do_#{@deal.contact.id}" do %>
Boaa essas trocas!

2024-01-17 10:12 UTC, douglara commented on spec/controllers/accounts/deals_controller_spec.rb
> +          create(:event, account: account, deal: deal, kind: 'activity')
Hmmm acho que se colocar na factory pode ser melhor que já re aproveita no futuro

2024-01-17 10:12 UTC, douglara commented on app/views/accounts/contacts/events/edit.html.erb
> +        <% if @event.kind == 'chatwoot_message' %>
Isso aqui foi por conta da troca de nome da partial `_chatwoot_message` para `_chatwoot_connect_message` né? Mas porque trocar para `_chatwoot_connect_message`? Achei que esse trecho ficou pior assim

2024-01-17 10:12 UTC, douglara commented on app/javascript/controllers/event_send_message_form_controller.js
> +        this.checkBoxAutoDoneTarget.checked = true
Isso aqui não seria mais interessante fazer lá na construção do forms?

2024-01-17 10:12 UTC, douglara commented on app/javascript/controllers/event_send_message_form_controller.js
> +        });
Aqui vai ser sempre um né?
Acho que não precisaria fazer esse forEach, talvez como:
```suggestion
        this.element.querySelector('.radio-button-div').setAttribute('aria-checked', 'false');
```

2024-01-17 10:12 UTC, douglara commented on app/javascript/controllers/event_send_message_form_controller.js
> +            // this.scheduledAtFormTarget.style.display = '';
Boa fazermos uma call para vermos esse trecho

2024-01-17 18:39 UTC, YukioArie commented on app/models/deal.rb
>    end
Acabei mudando next_event_scheduled para next_event_planned. A diferença entre o planned e o scheduled é q um o auto_done tem q ser true e o outro n precisa. Nesse caso a gnt tem q pegar o ultimo evento independente do valor do auto_done, então temos que pegar da coleção do planned.

2024-01-17 19:17 UTC, YukioArie commented on app/views/accounts/contacts/events/edit.html.erb
> +        <% if @event.kind == 'chatwoot_message' %>
Na verdade essa partial de form do chatwoot sempre teve esse nome `chatwoot_connect_message`, e antes n dava para editar um event do tipo `chatwoot_message` pq ele estava gerando o caminho da url de forma errada, assim: `"components/events/form/#{@event.kind}"`, e não existe uma partial chamada chatwoot_message no formulario, o nome da partial que está lá é `_chatwoot_connect_message`. Se eu deixar o trecho sem a alteração que eu fiz, ele vai dar esse erro.

2024-01-17 19:18 UTC, YukioArie commented on app/javascript/controllers/event_send_message_form_controller.js
> +        this.checkBoxAutoDoneTarget.checked = true
Temos que conversar sobre isso

2024-01-17 19:18 UTC, YukioArie commented on app/javascript/controllers/event_send_message_form_controller.js
> +        });
Temos que conversar sobre isso

2024-01-17 19:18 UTC, YukioArie commented on app/javascript/controllers/event_send_message_form_controller.js
> +            // this.scheduledAtFormTarget.style.display = '';
Temos que conversar sobre isso

2024-01-18 00:15 UTC, YukioArie commented on spec/controllers/accounts/deals_controller_spec.rb
> +          create(:event, account: account, deal: deal, kind: 'activity')
Boa!

2024-01-18 11:22 UTC, YukioArie commented on app/views/accounts/contacts/events/edit.html.erb
> +        <% if @event.kind == 'chatwoot_message' %>
Replace chatwoot_connect_message

2024-01-19 02:01 UTC, YukioArie commented on app/javascript/controllers/event_send_message_form_controller.js
> +        });
Esse codigo é para tirar o estilo de selecionado das divs que contem o radio button:
![image](https://github.com/douglara/woofed-crm/assets/45243355/bfd5e801-bd2e-4935-8df5-28d0d61b02c5)
Esse estilo roxo é aplicado quando uma div tem o aria-checked = true. Eu reseto de todos os dois e seto na linha seguinte a div que será selecionada de acordo com a div que o usuário clicou. Fiz algumas alterações no nome para ficar mais claro, esse caso eu renomeei para `send-now-wrapper`./

2024-01-19 02:03 UTC, YukioArie commented on app/javascript/controllers/event_send_message_form_controller.js
> +            // this.scheduledAtFormTarget.style.display = '';
Refatorei ele, acredito que agora ficou um pouco melhor de entender

2024-01-22 10:54 UTC, douglara requested changes

2024-01-22 10:54 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +        <% unless (event.kind == "chatwoot_message" || event.kind == "wpp_connect_message") && event.done? %>
Aqui acho que acabou passando, pelo que vi talvez precise alterar o método `editable?`

2024-01-23 00:48 UTC, YukioArie commented on app/views/accounts/contacts/events/_event.html.erb
> +        <% unless (event.kind == "chatwoot_message" || event.kind == "wpp_connect_message") && event.done? %>
Boa, fiz a alteração 🚀

2024-01-23 10:27 UTC, douglara requested changes

2024-01-23 10:27 UTC, douglara commented on app/models/event.rb
> +    return false if done == true || !scheduled_at.present?
`!scheduled_at.present?` e `scheduled_at.blank?` são equivalentes mas acho o `scheduled_at.blank?` com menos esforço cognitivo para entender.

2024-01-23 10:27 UTC, douglara commented on spec/models/event_spec.rb
> +  end
Boaa simples e eficiente!

2024-01-23 10:27 UTC, douglara commented on app/models/event.rb
> +    ['note', 'activity'].include?(kind) || !((self.chatwoot_message? || self.wpp_connect_message? ) && self.done?)
Hmmm acho que tem algumas formas mais simples de fazer esses if.
Segue algumas sugestões:


1
```suggestion

  def editable?
    return true if ['note', 'activity'].include?(kind)
    return true if ['chatwoot_message', 'wpp_connect_message'].include?(kind) && !done?
    return false
  end

```


2
```suggestion

  def always_editable?
    ['note', 'activity'].include?(kind)
  end

  def editable?
    always_editable? || !done?
  end

```

2024-01-24 00:19 UTC, YukioArie commented on spec/models/event_spec.rb
> +  end
Showww!

2024-01-24 00:21 UTC, YukioArie commented on app/models/event.rb
> +    ['note', 'activity'].include?(kind) || !((self.chatwoot_message? || self.wpp_connect_message? ) && self.done?)
Achei a primeira opção mais fácil de entender, irei commitar ele mesmo. Valeu pelas sugestões.

2024-01-24 00:28 UTC, YukioArie commented on app/models/event.rb
> +    return false if done == true || !scheduled_at.present?
Vc tem razão, desfiz dessa alteração e refiz os testes e eles passaram sem erros.

2024-01-24 02:03 UTC, merged