Chatwoot contact past sync
douglara/woofed-crm pull request #219
Opened 2023-12-13 06:07 UTC by YukioArie

2024-01-06 22:11 UTC, douglara requested changes

2024-01-06 22:11 UTC, douglara commented on app/controllers/accounts/apps/chatwoots_controller.rb
> +      Accounts::Apps::Chatwoots::SyncExportContactsWorker.perform_async(current_user.account.id)
Aqui ficaria legal colocar em um caso de uso

2024-01-06 22:11 UTC, douglara commented on app/controllers/accounts/apps/chatwoots_controller.rb
> +    Accounts::Apps::Chatwoots::RemoveChatwootIdFromContactsWorker.perform_async(current_user.account.id)
Aqui ficaria legal colocar em um caso de uso

2024-01-06 22:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +    end
Indentação com problema

2024-01-06 22:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +        account.contacts.where.not(additional_attributes: nil).each do |contact|
Aqui da para fazer uma query que pega somente os que tem o campo chatwoot_id
Também vale fazer a query em batchs para o caso de ter muitos contatos
https://api.rubyonrails.org/classes/ActiveRecord/Batches.html

2024-01-06 22:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts_worker.rb
> +    end
Indentação com problema

2024-01-06 22:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_export_contacts.rb
> +        return response
Indentação com problema

2024-01-06 22:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_export_contacts_worker.rb
> +        Accounts::Apps::Chatwoots::SyncExportContacts.call(account)
Indentação com problema

2024-01-09 01:56 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_export_contacts_worker.rb
> +        Accounts::Apps::Chatwoots::SyncExportContacts.call(account)
Aqui ainda esta pendente

2024-01-09 01:57 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts_worker.rb
> +    end
Aqui ainda esta pendente

2024-01-09 02:11 UTC, douglara requested changes

2024-01-09 02:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +    account.contacts.where("additional_attributes -> 'chatwoot_id' IS NOT NULL").find_in_batches(batch_size: 30) do |group|
Aqui da para deixar o batch padrão de 1000 acho que é tranquilo pro banco essa quantidade

2024-01-09 02:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +      sleep(30)
Esse sleep acho que precisa não hehe

2024-01-09 02:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_export_contacts.rb
> +      sleep(30)
Hmmm aqui acho que pode ficar interessante mesmo deixar para diminuir o risco de sobrecarregarmos o servidor do chatwoot conectado.

2024-01-09 02:11 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_import_contacts.rb
> +              contacts_failed += 1
Aqui vale colocarmos um `Rails.logger.error("Error import contact from chatwoot #{contact.erros.inspect}, chatwoot: #{chatwoot.inspect}")
Assim quando ocorrer vamos ter mais ideia porque deu erro

2024-01-09 02:45 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts_worker.rb
> +    end
Alguns arquivos no meu vscode fica setado para da 4 espaçamentos 😢

2024-01-09 02:47 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +    account.contacts.where("additional_attributes -> 'chatwoot_id' IS NOT NULL").find_in_batches(batch_size: 30) do |group|
Precisamos conversar sobre isso amn

2024-01-09 03:00 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/sync_import_contacts.rb
> +              contacts_failed += 1
Boa ideia!

2024-01-12 09:59 UTC, douglara requested changes

2024-01-12 09:59 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/remove_chatwoot_id_from_contacts.rb
> +    return { ok: 'Contact chatwoot id was successfully removed.' }
```suggestion
    return { ok: 'Contacts chatwoot id was successfully removed.' }
```

2024-01-12 09:59 UTC, douglara commented on app/controllers/accounts/apps/chatwoots_controller.rb
> +    end
Bora criar um teste para validar esses controllers e os novos casos de uso

2024-01-16 10:37 UTC, douglara requested changes

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +      it 'returns unautorized' do
```suggestion
      it 'returns unauthorized' do
```

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +      it 'returns unautorized' do
```suggestion
      it 'returns unauthorized' do
```

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +      end
Boaaa ficou massa esses testes aqui!

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +      it 'returns unautorized' do
```suggestion
      it 'returns unauthorized' do
```

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +      it 'returns unautorized' do
```suggestion
      it 'returns unauthorized' do
```

2024-01-16 10:37 UTC, douglara commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +        delete "/accounts/#{account.id}/apps/chatwoots/#{chatwoot.id}"
Aqui da pra envolver naquele bloco de change igual dos outros testes, mais ou menos assim
```ruby
expect do
    
end.to change(Apps::Chatwoot, :count).by(-1)```

2024-01-16 10:37 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +        Sidekiq::Testing.inline! do
Como todos os testes desse arquivo são com o `Sidekiq::Testing.inline! do`
Conseguimos colocar em volta de um around, mais ou menos assim

```ruby
around(:each) do |test|
  Sidekiq::Testing.inline! do
      test.run
  end
end```

2024-01-16 10:37 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +          .to_return(status: 200, body: contact_list_page_3, headers: { 'Content-Type' => 'application/json' })
Boaa!

2024-01-16 10:37 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +          expect(account.contacts.count).to eq(3)
Aqui precisa checar se todos estão com o chatwoot_id para confirmar que foram enviados para o chatwoot

2024-01-16 10:37 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +            end
Bons testes

2024-01-16 10:37 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/sync_import_contacts.rb
> +  def self.update_or_create_contact(chatwoot)
Esse método vai precisar de algumas refatorações, mas ai vamos fazendo gradualmente

2024-01-16 23:17 UTC, YukioArie commented on spec/controllers/accounts/apps/chatwoots_controller_spec.rb
> +        delete "/accounts/#{account.id}/apps/chatwoots/#{chatwoot.id}"
Boa ideia! 🚀

2024-01-16 23:24 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/sync_import_contacts.rb
> +  def self.update_or_create_contact(chatwoot)
Sim, ele ta meio grandinho neh hehe

2024-01-16 23:47 UTC, YukioArie commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +        Sidekiq::Testing.inline! do
O problema é que se colocamos essa linha para rodar em todos os testes, no começo do describe, ele acaba rodando dentro tbm os let. Ex: let!(:contact) { create(:contact, account: account) }. daí ele acaba passando tbm pelo fluxo de importar e exportar o contato, que é o q acontece quando criamos um contato, mas n queremos que ele tenha esse comportamento quando criamos um contato com o let ne, e daí para cada let criado dentro do teste eu terei q fazer vários stubs de url. N sei se deu para entender, mas posso te explicar amn.

2024-01-17 00:24 UTC, YukioArie commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +          expect(account.contacts.count).to eq(3)
Na verdade essa situação é para verificar se a quantidade de contatos irá ser alterado passando por essa condição. Lembrando que quando fazemos o sync dos contatos, ele irá importar todos os contatos do chatwoot, e depois exportar os contatos que por ventura existe no woofed mas não existe no chatwoot, que serão os contatos que não possuião o chatwoot_id no additional attributes logo após a importação dos contatos do chatwoot. Nesse arquivo, estou testando somente o fluxo de importar os contatos do chatwoot, nesse teste que vc mencionou, tem um contato que não terá o chatwoot_id, que é o contato criado no let. Esse contato terá o chatwoot_id, logo após passar pelo outro fluxo do sync_export_contatcts, que criará esse contato no chatwoot e preencherá o chatwoot_id no additional attributes. Esse fluxo eu testei em outro arquivo chamado sync_export_contacts_spec.

2024-01-17 00:28 UTC, YukioArie commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +          expect(account.contacts.count).to eq(3)
Esse teste está com a descrição errada, pois ele só criará no chatwoot no fluxo do sync_export_contact. Irei alterar para 
```ruby
      context 'if contact exist in woofed but not in chatwoot' do
        let!(:contact) { create(:contact, account: account) }
        it 'should ignore contact' do
          Sidekiq::Testing.inline! do
            Accounts::Apps::Chatwoots::SyncImportContactsWorker.perform_async(chatwoot.id)
          end
          expect(account.contacts.count).to eq(3)
        end
      end
```

2024-01-17 10:21 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +          expect(account.contacts.count).to eq(3)
Entendi boaa blz!

2024-01-17 10:21 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +        Sidekiq::Testing.inline! do
Entendi blzz!

2024-01-17 10:25 UTC, douglara approved these changes

2024-01-17 10:25 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/sync_import_conctacts_spec.rb
> +            it 'should replace woofed contact tags to chatwoot contact tags ' do
```suggestion
            it 'should replace woofed contact tags from chatwoot contact tags ' do
```

2024-01-17 10:25 UTC, merged