Add register user devise login
douglara/woofed-crm pull request #227
Opened 2023-12-16 03:59 UTC by YukioArie

2023-12-20 02:20 UTC, douglara commented on app/controllers/application_controller.rb
> +  end
Será que não tem como colocar isso em outro controller? Se tiver algum especifico do devise

2023-12-20 02:20 UTC, douglara commented on app/controllers/application_controller.rb
> +  end
Um testzim seria bacana hehe

2023-12-20 10:37 UTC, douglara commented
@YukioArie aproveitando que tu esta mexendo nessa página conseguiria colocar um campo de telefone no usuário?

2024-01-11 02:00 UTC, douglara requested changes

2024-01-11 02:00 UTC, douglara commented on app/models/user.rb
> +  accepts_nested_attributes_for :account, reject_if: ->(attributes){ attributes['name'].blank? }
Hmm essa validação será que não da pra jogar no model account?
`reject_if: ->(attributes){ attributes['name'].blank? }`

2024-01-11 02:00 UTC, douglara commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
Hmmm tem um maneira melhor de implementar esse fluxo aqui, bora fazer em call

2024-01-11 02:00 UTC, douglara commented on .env.sample
> +ENABLE_USER_SIGNUP=false
Hmmm aqui no ambiente de dev talvez seja melhor deixar ativo

2024-01-11 02:00 UTC, douglara commented on app/views/devise/registrations/new.html.erb
> +      </div> -->
Da para remover esse comentários

2024-01-11 02:00 UTC, douglara commented on app/views/devise/registrations/new.html.erb
> +
```suggestion
```

2024-01-11 02:00 UTC, douglara commented on app/views/devise/registrations/new.html.erb
> +        <%= link_to "Esqueceu a senha?", new_password_path(resource_name), class: "typography-text-m-lh150 text-dark-gray-palette-p1 hover:text-brand-palette-02 hidden" %>
Aqui no fluxo de criar uma conta não precisa desses links de "Esqueceu a senha"

2024-01-11 02:00 UTC, douglara commented on app/views/devise/sessions/new.html.erb
> +
```suggestion
```

2024-01-11 02:00 UTC, douglara commented on app/views/devise/sessions/new.html.erb
> +<div class="text-center typography-text-m-lh150 text-dark-gray-palette-p1 mt-5">
Aqui correção da indentação

2024-01-11 02:00 UTC, douglara commented on app/views/layouts/devise.html.erb
> +    <%= csrf_meta_tags %>
Hmm aqui não daria para o usar o layout que temos para a página de login?

2024-01-11 02:00 UTC, douglara commented on spec/controllers/accounts/settings/webhooks_controller_spec.rb
> +            invalid_params = { webhook: { status: '' } }
Acho que entrou por engano

2024-01-12 04:44 UTC, YukioArie commented on app/models/user.rb
> +  accepts_nested_attributes_for :account, reject_if: ->(attributes){ attributes['name'].blank? }
Essa validação já está sendo feita no accout: 
```ruby
  validates :name, presence: true
``` 
Eu acabei colocando ele sem me notar q já existia essa validação no model account 😄 , Vou remover ele aqui.

2024-01-12 04:47 UTC, YukioArie commented on .env.sample
> +ENABLE_USER_SIGNUP=false
Concordo tbm.

2024-01-12 04:51 UTC, YukioArie commented on app/views/devise/registrations/new.html.erb
> +        <%= link_to "Esqueceu a senha?", new_password_path(resource_name), class: "typography-text-m-lh150 text-dark-gray-palette-p1 hover:text-brand-palette-02 hidden" %>
Tem razão! Acho que na hora que eu fui reaproveitar o layout da outra pagina do devise, eu acabei esquecendo de tirar ele hehe

2024-01-12 05:06 UTC, YukioArie commented on app/views/layouts/devise.html.erb
> +    <%= csrf_meta_tags %>
Na verdade não temos um layout para a pagina de logins, o layout dele por padrão é o application. Eu criei esse layout para que ele possa ser para as páginas de cadastro e login do devise. Achei importante ter um layout para ele, pois ele é uma pagina que tem as paginas parecidas ( o q muda só é os formularios ).

2024-01-12 05:11 UTC, YukioArie commented on spec/controllers/accounts/settings/webhooks_controller_spec.rb
> +            invalid_params = { webhook: { status: '' } }
Eu corrigi esse erro de teste aqui pq eu encontrei ele quando estava trabalhando nesse card. Por ser algo simples eu acabei criando um commit por aqui mesmo, ao invés de criar um pull request ou um commit na branch principal só por conta dessa alteração.

2024-01-12 05:14 UTC, YukioArie commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
Bora 🚀

2024-01-22 19:50 UTC, merged