Add welcome page
douglara/woofed-crm pull request #228
Opened 2023-12-16 08:55 UTC by YukioArie

2023-12-19 10:55 UTC, douglara requested changes
Bora colocar uns testes ai heheh

2023-12-19 10:55 UTC, douglara commented on app/controllers/accounts/pipelines_controller.rb
> +      @pipeline = Pipeline.find(params[:id])
Aqui precisamos pegar o pipeline que o usuário/account tem acesso

2023-12-19 10:55 UTC, douglara commented on app/controllers/accounts/welcome_controller.rb
> +class Accounts::WelcomeController < InternalController
Aqui da indentação esta errada

2024-01-06 21:27 UTC, douglara requested changes

2024-01-06 21:27 UTC, douglara commented on app/controllers/accounts/pipelines_controller.rb
> +      @pipeline = current_user.pipelines.find(params[:id])
Boaa!

2024-01-06 21:27 UTC, douglara commented on app/controllers/accounts/pipelines_controller.rb
> +      @pipeline = current_user.pipelines.find(params[:id])
![image](https://github.com/douglara/woofed-crm/assets/14988496/5a70c1d6-4cbd-4c9c-a894-d2ebaaf08447)

Acho que precisa adicionar esse relacionamento no model

2024-01-07 16:30 UTC, YukioArie commented on app/controllers/accounts/pipelines_controller.rb
> +      @pipeline = current_user.pipelines.find(params[:id])
Eu errei mesmo :sweat_smile:, o certo é colocar o account antes de pipelines, pq o pipeline está associado a uma conta e não a um usuário 
```ruby

@pipeline = current_user.account.pipelines.find(params[:id])

2024-01-11 02:37 UTC, douglara requested changes

2024-01-11 02:37 UTC, douglara commented on app/controllers/accounts/pipelines_controller.rb
> +      @pipeline = current_user.account.pipelines.find(params[:id])
Boaa!

2024-01-11 02:37 UTC, douglara commented on spec/controllers/accounts/pipelines_controller_spec.rb
> +          end.to change(Pipeline, :count).by(0)
Esse expect change nesse caso não tem necessidade.

2024-01-11 02:37 UTC, douglara commented on spec/controllers/accounts/pipelines_controller_spec.rb
> +          end.to change(Pipeline, :count).by(0)
Aqui também

2024-01-12 05:18 UTC, YukioArie commented on spec/controllers/accounts/pipelines_controller_spec.rb
> +          end.to change(Pipeline, :count).by(0)
Show 🎸

2024-01-15 10:47 UTC, douglara approved these changes

2024-01-15 10:47 UTC, merged