Improve description and layout from user_not_found page
douglara/woofed-crm pull request #232
Opened 2023-12-22 19:56 UTC by YukioArie

![image](https://github.com/douglara/woofed-crm/assets/45243355/380755c8-aecb-414e-8cc6-82f907ae9e53)

2024-01-12 09:40 UTC, douglara requested changes
Vejo que o layout atual centralizando as informações esta mais interessante

Atual:
![image](https://github.com/douglara/woofed-crm/assets/14988496/0c9a2491-d816-409f-a62e-d2e7b300d69f)

Branch:
![image](https://github.com/douglara/woofed-crm/assets/14988496/f0415c6c-c6b5-4fd5-880d-9fb1b1598153)

2024-01-12 09:40 UTC, douglara commented on app/views/apps/chatwoots/user_not_found.html.erb
> +    <%= link_to "http://app-beta.woofedcrm.com/accounts/1/users" , target: :_blank,
Aqui o valor do link esta fixo, o ideal seria puxar o endereço dinâmico da instalação e também o id da account.

Exemplo:
Meu chatwoot local esta na URL: https://happy-zebra-28.hooks.n8n.cloud
![image](https://github.com/douglara/woofed-crm/assets/14988496/257f3781-4eef-42fe-8e85-054d98b739d8)

Mas esta me jogando para o: `https://app-beta.woofedcrm.com`

![image](https://github.com/douglara/woofed-crm/assets/14988496/2f3f8f1b-d73e-498a-a069-da144638f2dc)

2024-01-16 00:49 UTC, YukioArie commented
![image](https://github.com/douglara/woofed-crm/assets/45243355/1f5bb6dc-2c2c-4168-8025-cac339dbe725)

2024-01-16 10:42 UTC, douglara approved these changes

2024-01-16 10:42 UTC, douglara commented on app/views/apps/chatwoots/user_not_found.html.erb
> +    <%= link_to "#{ ENV['FRONTEND_URL']}/accounts/#{@chatwoot.account_id}/users/new" , target: :_blank,
Hmmm aqui talvez podemos trocar para os helpers de url mesmo.
Seria bom ter um teste para esses controllers para termos mais segurança ao mexer com eles mas bora puxar em outro card para não estender tanto, o código já ficou melhor do que estava heheh boa!

2024-01-16 10:44 UTC, merged