Add sync chatwoot labels
douglara/woofed-crm pull request #234
Opened 2024-01-05 07:30 UTC by YukioArie

2024-01-12 10:20 UTC, douglara requested changes
Aqui bora seguir o formato visual do Woofed colocando o input na direita
![image](https://github.com/douglara/woofed-crm/assets/14988496/47ffe591-f96e-43df-8f33-a5bd3e7f4af3)

![image](https://github.com/douglara/woofed-crm/assets/14988496/d823e7eb-3ea8-4747-87df-af06c4011a3f)

![image](https://github.com/douglara/woofed-crm/assets/14988496/bfddc069-e911-40da-99bc-8196fb184ba7)



Peguei também a seguinte situação:
A tag não existe no chatwoot, adicionamos no Woofed ela acaba não enviando ou adicionando no chatwoot segue exemplo

![image](https://github.com/douglara/woofed-crm/assets/14988496/d95d918a-0127-415b-ad92-3b5b82a4600c)


![image](https://github.com/douglara/woofed-crm/assets/14988496/00601c08-7d39-4d2f-89e9-d038550f2e9b)


Nessa situação seria legal criar a tag no chatwoot

2024-01-12 10:20 UTC, douglara commented on app/controllers/accounts/contacts_controller.rb
> +                                    custom_attributes: {}).merge(label_list: labels_list_formatted_params)
Hmm será que algo nesse sentido não ficaria mais simples?

```suggestion
    params.require(:contact).permit(:full_name, :phone, :email,
                                    custom_attributes: {}, label_list:{})
```

```suggestion
    params.require(:contact).permit(:full_name, :phone, :email,
                                    custom_attributes: {}, label_list:[])
```

2024-01-12 10:20 UTC, douglara commented on app/javascript/packs/application.js
> +import '@yaireo/tagify/src/tagify';
Precisa desses dois aqui mesmo?

2024-01-12 10:20 UTC, douglara commented on app/javascript/packs/application.js
> +  new Tagify(document.querySelector('input[id=contact_chatwoot_conversations_label_list]'));
Em vez de colocar por id será que por um class css não ficaria melhor?
Algo como `field-tags`

2024-01-12 12:00 UTC, douglara commented
Como resolver visualmente quando tiver muitas labels?

2024-01-12 18:46 UTC, YukioArie commented on app/javascript/packs/application.js
> +import '@yaireo/tagify/src/tagify';
Sim, o primeiro importa o arquivo js do tagify, e o segundo importa o arquivo de styles do tagify

2024-01-16 11:02 UTC, douglara commented
Tem um bug visual aqui no show hehe
![image](https://github.com/douglara/woofed-crm/assets/14988496/8b71631c-9946-49b2-ac6e-baf3fe8e302b)

Ficou topss o edit heimm boa!
![image](https://github.com/douglara/woofed-crm/assets/14988496/d0a01113-2114-436c-97ad-86be62e2de41)

2024-01-16 11:02 UTC, douglara requested changes

2024-01-16 11:02 UTC, douglara commented on app/javascript/packs/application.js
> +import '@yaireo/tagify/src/tagify';
Como esta lá no controller stimulus precisa ter aqui também?

2024-01-17 10:32 UTC, douglara requested changes
Ficando bonitooo haha!

Aqui acho que dessa forma segue melhor o padrão visual
Atual
![image](https://github.com/douglara/woofed-crm/assets/14988496/e7490840-9ae3-495c-9967-e079cbc2ff90)
Sugestão

![image](https://github.com/douglara/woofed-crm/assets/14988496/e089f5f8-ec96-4e44-86e6-1db04ab66ec8)

2024-01-25 20:27 UTC, YukioArie commented
![image](https://github.com/douglara/woofed-crm/assets/45243355/0f445406-b086-4732-9cc6-10951ddc627f)
Achei legal esse estilo

2024-01-29 11:48 UTC, douglara requested changes

2024-01-29 11:48 UTC, douglara commented on app/views/accounts/deals/details/_show.html.erb
> +        <% if model["#{f}"].present? || model.send(f).present?%>
Hmm aqui em vez de adicionar o `|| model.send(f).present?` será que adicionando na variável `FORM_FIELDS` não funciona?
Seria o `label_list` e `chatwoot_conversations_label_list`

2024-01-29 11:48 UTC, douglara commented on app/views/components/_list_labels.html.erb
> +      <p class="typography-sub-text-m-lh150"><%= label %></p>
Massaaa heim ficou tops o layout

2024-01-29 20:50 UTC, YukioArie commented on app/views/accounts/deals/details/_show.html.erb
> +        <% if model["#{f}"].present? || model.send(f).present?%>
Removi model["#{f}"].present? e continuou funcionando perfeitamente.

2024-01-29 20:51 UTC, YukioArie commented on app/views/components/_list_labels.html.erb
> +      <p class="typography-sub-text-m-lh150"><%= label %></p>
🚀

2024-01-30 10:16 UTC, douglara approved these changes

2024-01-30 10:16 UTC, douglara commented on app/views/accounts/deals/details/_show.html.erb
> +        <% if model.send(f).present? %>
Boaa!

2024-01-30 10:16 UTC, merged