Add create instance use case evolutionapi
douglara/woofed-crm pull request #240
Opened 2024-01-23 04:27 UTC by YukioArie

2024-01-25 10:52 UTC, douglara requested changes

2024-01-25 10:52 UTC, douglara commented on app/models/apps/evolution_api.rb
> +  belongs_to :account
Esse relacionamento já é adicionado no `include Applicable` 😁

2024-01-25 10:52 UTC, douglara commented on app/use_cases/accounts/apps/evolution_api/instance/create.rb
> +        "QRCODE_UPDATED"
Aqui vamos precisar de mais eventos para poder receber as mensagens

2024-01-25 10:52 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :status
Bora trocar uma ideia sobre valores padrões e null

2024-01-25 10:52 UTC, douglara commented on db/migrate/20240123203201_add_additional_attributes_to_apps_evolution_api.rb
> +    add_column :apps_evolution_apis, :additional_attributes, :jsonb
Como ainda esta em desenvolvimento esse PR, da para adicionar isso na outra migração

2024-01-25 10:52 UTC, douglara commented on spec/integration/use_cases/accounts/apps/evolution_api/instance/create_spec.rb
> +        end
Boa ficou maneiro os testes

2024-01-25 10:52 UTC, douglara commented on spec/models/apps/evolution_api_spec.rb
> +      expect(result.length).to eq(20)
Hmmm esse teste não esta validando muito o que o método faz...
Para testarmos ele não vai ser tão simples também, eu optaria em não fazer o testes nesse momento.

2024-01-25 10:52 UTC, douglara commented on app/models/apps/evolution_api.rb
> +    'active': 'active',
Esse active pode confundir com o campo active booleano, acho que seria interessante utilizarmos outro nome ou algum prefixo

2024-01-25 12:03 UTC, douglara requested changes

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :status
O status podemos renomear para `connection_status`, habilitar o not null e deixar o valor padrão como inativo

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.boolean :active
O active habilitar o not null e deixar o valor padrão como ativo

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :endpoint_url
O endpoint_url habilitar o not null e deixar o valor padrão como string vazia e adicionar no model a validação para não poder ser vazia `validate present`

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :token
O token habilitar o not null e deixar o valor padrão como string vazia e adicionar no model a validação para não poder ser vazia validate present

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :phone
O phone habilitar o not null e deixar o valor padrão como string vazia

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +      t.string :name
O token habilitar o not null e deixar o valor padrão como string vazia e adicionar no model a validação para não poder ser vazia validate present

2024-01-25 12:03 UTC, douglara commented on db/migrate/20240123014507_create_apps_evolution_apis.rb
> +
Adicionar o campo instance

2024-01-25 19:45 UTC, YukioArie commented on app/models/apps/evolution_api.rb
> +  belongs_to :account
Show! Essa linha ele gerou por padrão logo após criar a migração de criação da evolution api

2024-01-25 20:16 UTC, YukioArie commented on spec/integration/use_cases/accounts/apps/evolution_api/instance/create_spec.rb
> +        end
Showww!

2024-01-26 10:51 UTC, douglara approved these changes

2024-01-26 10:51 UTC, douglara commented on app/builders/evolution_api_builder.rb
> +    @evolution_api
Esse código seria massa adicionar junto com o fluxo de criação do model hehe mas ta de boas ai revemos ele no outro PR

2024-01-26 10:51 UTC, merged