Add evolution api fronted
douglara/woofed-crm pull request #249
Opened 2024-02-01 08:29 UTC by YukioArie

2024-02-01 10:59 UTC, douglara requested changes

2024-02-01 10:59 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +      @evolution_api = Apps::EvolutionApi.find(params['evolution_api_id'])
```suggestion
      @evolution_api = Apps::EvolutionApi.find(params[:id])
```

Será que assim já não funciona?

2024-02-01 10:59 UTC, douglara commented on app/views/accounts/apps/evolution_apis/pair_qr_code.html.erb
> +    <li>2.Toque em <b class="text-dark-gray-palette-p2">Mais opções</b> no Android ou em <b class="text-dark-gray-palette-p2">Configurações</b> no iphone.</li>
Aqui da para melhorar a identação

2024-02-01 10:59 UTC, douglara commented on app/views/accounts/settings/index.html.erb
> +          <p class="typography-sub-text-r-lh150 text-dark-gray-palette-p3">Configure sua conexão com whatsapp (EvolutionAPI)</p>
```suggestion
          <p class="typography-sub-text-r-lh150 text-dark-gray-palette-p3">Configure sua conexão com whatsapp</p>
```

Acho que aqui da pra deixar sem mesmo hehe :smiley:

2024-02-01 10:59 UTC, douglara commented on app/views/layouts/shared/_navbar.html.erb
> +  <% elsif controller_path == 'accounts/apps/evolution_apis'  %>
Aiaia esse arquivo 😂

2024-02-01 10:59 UTC, douglara commented on app/views/layouts/shared/_navbar_evolution_api.html.erb
> +  <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">Conexões - EvolutionApi</h1>
```suggestion
  <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">Conexões Whatsapp</h1>
```

2024-02-01 10:59 UTC, douglara commented on config/routes.rb
> +        resources :evolution_apis do
```suggestion
        resources :evolution_apis, except: [:destroy, :update] do
```

2024-02-01 10:59 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +
Bora criar uns testes de controller

2024-02-01 12:17 UTC, YukioArie commented on app/views/accounts/settings/index.html.erb
> +          <p class="typography-sub-text-r-lh150 text-dark-gray-palette-p3">Configure sua conexão com whatsapp (EvolutionAPI)</p>
kkkkkkkkkkkkkkkkkkkkkk

2024-02-01 12:17 UTC, YukioArie commented on app/views/layouts/shared/_navbar.html.erb
> +  <% elsif controller_path == 'accounts/apps/evolution_apis'  %>
kkkkkkkkkkkkkkkkkkkkkk

2024-02-02 06:55 UTC, YukioArie commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +      @evolution_api = Apps::EvolutionApi.find(params['evolution_api_id'])
Infelizmente não 😢 
![image](https://github.com/douglara/woofed-crm/assets/45243355/8662977b-5e6d-40d7-a1ad-ecde7c21f38c)

2024-02-02 07:32 UTC, YukioArie commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +      @evolution_api = Apps::EvolutionApi.find(params['evolution_api_id'])
Para a rota do pair_qr_code n, mas eu acabei fazendo essa alteração e na action do pair_qr_code eu coloquei esse codigo. Ficou assim: 
```ruby
  def pair_qr_code
    @evolution_api = current_user.account.apps_evolution_apis.find(params['evolution_api_id'])
  end

  private
    def set_evolution_api
      @evolution_api = current_user.account.apps_evolution_apis.find(params[:id])
    end
```

2024-02-03 08:32 UTC, YukioArie commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +
Boa, acabei de criar 😄

2024-02-06 09:58 UTC, douglara requested changes
Atualizar o arquivo:

app/use_cases/accounts/apps/evolution_apis/instance/create.rb
```ruby
"qrcode": false
```

E adicionar os eventos:
```
    "MESSAGES_SET",
    "MESSAGES_UPSERT",
    "MESSAGES_UPDATE",
    "MESSAGES_DELETE",
    "SEND_MESSAGE",
    "CONTACTS_SET",
    "CONTACTS_UPSERT",
    "CONTACTS_UPDATE",
    "PRESENCE_UPDATE",
    "CHATS_SET",
    "CHATS_UPSERT",
    "CHATS_UPDATE",
    "CHATS_DELETE",
    "GROUPS_UPSERT",
    "GROUP_UPDATE",
    "GROUP_PARTICIPANTS_UPDATE",
    "CONNECTION_UPDATE",    
     "CALL"
```

2024-02-06 09:58 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +    @evolution_api = current_user.account.apps_evolution_apis.find(params[:id])
Boaa!

2024-02-06 09:58 UTC, douglara commented on app/views/accounts/apps/evolution_apis/pair_qr_code.html.erb
> +      2.Toque em <b class="text-dark-gray-palette-p2">Mais opções</b> no Android ou em <b class="text-dark-gray-palette-p2">Configurações</b> no iphone.
```suggestion
      2.Toque em <b class="text-dark-gray-palette-p2">Mais opções</b> no Android ou em <b class="text-dark-gray-palette-p2">Configurações</b> no iPhone.
```

2024-02-06 09:58 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +    params.require(:apps_evolution_api).permit(:name, :token, :instance, :endpoint_url)
```suggestion
    params.require(:apps_evolution_api).permit(:name)
```

Pelos testes automatizado e testes manuais que eu fiz aqui da para permitirmos somente o name por enquanto.

2024-02-06 09:58 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +        format.json { render :create, status: :created }
Aqui seria para suportar api também?

2024-02-06 09:58 UTC, douglara commented on app/controllers/apps/evolution_apis_controller.rb
> +  skip_before_action :verify_authenticity_token
Hmmm aqui como é um endpoint que vai receber apenas requisições JSON de api talvez trocar o controller base seja mais interessante e também aplica otimizações nos cenários de API

```suggestion
class Apps::EvolutionApisController < Api::V1::PublicController
```

2024-02-06 09:58 UTC, douglara commented on app/models/apps/evolution_api.rb
> +  # validate :validate_evolution_api, on: :create
Essa validação seria sobre o que?

2024-02-06 09:58 UTC, douglara commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +  end
Para unificar esses dois carinhas você pode utilizar assim nas rotas
![image](https://github.com/douglara/woofed-crm/assets/14988496/b64495e1-fdcb-44db-a160-c91135406824)

Segue mais detalhes:
https://tadhao.medium.com/member-vs-collection-in-rails-routes-ade10c8c5d19

2024-02-06 09:58 UTC, douglara commented on app/views/accounts/apps/evolution_apis/_qrcode.html.erb
> +
```suggestion
```

2024-02-06 09:58 UTC, douglara commented on app/views/accounts/apps/evolution_apis/_qrcode.html.erb
> +</div>
Aqui da pra corrigir a identação

2024-02-06 09:58 UTC, douglara commented on app/views/accounts/apps/evolution_apis/_qrcode.html.erb
> +  <%= link_to account_apps_evolution_api_refresh_qr_code_path(evolution_api.account, evolution_api), method: :post, class:"bg-[#5FC8BC] h-64 w-64 rounded-full mx-auto lg:m-0 flex justify-center items
Ficou massaa heim!

2024-02-06 19:27 UTC, YukioArie commented on app/controllers/accounts/apps/evolution_apis_controller.rb
> +        format.json { render :create, status: :created }
Isso, mas removi ele 😄

2024-02-06 19:28 UTC, YukioArie commented on app/controllers/apps/evolution_apis_controller.rb
> +  skip_before_action :verify_authenticity_token
Show!

2024-02-06 19:55 UTC, YukioArie commented on app/views/accounts/apps/evolution_apis/_qrcode.html.erb
> +</div>
Boa

2024-02-06 19:55 UTC, YukioArie commented on app/views/accounts/apps/evolution_apis/_qrcode.html.erb
> +  <%= link_to account_apps_evolution_api_refresh_qr_code_path(evolution_api.account, evolution_api), method: :post, class:"bg-[#5FC8BC] h-64 w-64 rounded-full mx-auto lg:m-0 flex justify-center items
topzzzz

2024-02-06 20:01 UTC, YukioArie commented on app/models/apps/evolution_api.rb
> +  # validate :validate_evolution_api, on: :create
Eu tinha adicionado uma validação para q se a criação de instancia na evolution_api retornasse algum erro, fosse exibido para o usuário. Porém acabei removendo pq n estava funcionando direito. A função da validação era esse: 
```ruby
  def validate_evolution_api
     result = Accounts::Apps::EvolutionApis::Instance::Create.call(self)
     if result.key?(:error)
       errors.add(:error, "#{result[:error]['response']['message']}")
     end
  end
```

2024-02-07 10:23 UTC, douglara approved these changes
Parabénsss @YukioArie ficou muito boaa essa implementação ❤️

2024-02-07 10:23 UTC, merged