Add backend attachments
douglara/woofed-crm pull request #258
Opened 2024-02-21 02:08 UTC by YukioArie

2024-02-21 07:53 UTC, douglara requested changes

2024-02-21 07:53 UTC, douglara commented on app/models/attachment.rb
> +  belongs_to :event
Hmmm aqui como vamos em breve adicionar no produto acho que poderia ser um relacionamento polimorfico
https://www.campuscode.com.br/conteudos/associacao-polimorfica

2024-02-21 07:53 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_attachments.rb
> +      attachment
Hmmm o chatwoot permite que uma mensagem tenha vários attachments mas do nosso lado apenas um.
Acho que dessa forma fica ruim pois os eventos que são attachments ficam sem id ou meio desconectado da mensagem original.
Talvez seja necessário nosso evento suportar vários attachments

2024-02-21 07:53 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/events/message.rb
> +    attachments = Accounts::Apps::Chatwoots::Webhooks::ImportAttachments.call(chatwoot, contact, webhook)
Talvez o import import_attachments pode ser um caso de uso dentro do ImportMessage

2024-02-21 07:53 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +    return 'Message content can not be blank' if webhook['content'].blank?
Essa validação é necessária mesmo?
Pensando no caso de uma mensagem com texto em branco e um arquivo.

2024-02-21 07:53 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +    webhook.dig('sender', 'type') == 'user' if webhook.dig('sender', 'id').present?
Esse método pode retornar nil?

2024-02-21 21:50 UTC, YukioArie commented on app/models/attachment.rb
> +  belongs_to :event
Maneiro!

2024-02-21 21:52 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/events/message.rb
> +    attachments = Accounts::Apps::Chatwoots::Webhooks::ImportAttachments.call(chatwoot, contact, webhook)
Acho melhor ficar fora mesmo, pois recebermos um webhook com uma mensagem e arquivos atrelados, iremos criar eventos separados  da mensagen e de cada arquivo

2024-02-21 21:56 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +    webhook.dig('sender', 'type') == 'user' if webhook.dig('sender', 'id').present?
Esse método é meio que impossivel retornar nil, pq a gnt sempre irá receber no evento do webhook esse sender:
```ruby
  "sender"=>{
    "id"=>2,
    "name"=>"Yukio",
    "available_name"=>"Yukio",
    "avatar_url"=>"",
    "type"=>"user",
    "availability_status"=>nil,
    "thumbnail"=>""
  }
``` 
Então ele sempre retornará falso ou verdadeiro. 
Obs: Eu nem alterei ele nesse commit, quem foi o ruboccop.

2024-02-21 21:57 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +    return 'Message content can not be blank' if webhook['content'].blank?
Então, se a gnt receber uma mensagem sem conteudo, e somente com arquivos, ele irá cair no outro caso de uso e irá criar os eventos para cada attachment.

2024-02-28 10:37 UTC, douglara requested changes

2024-02-28 10:37 UTC, douglara commented on app/models/attachment.rb
> +                    contact: 8 }
Aqui da para validarmos a presença do file e evitar um attachment sem arquivo

```suggestion
                    contact: 8 }
                    
  validates :file, presence: true
```

2024-02-28 10:37 UTC, douglara commented on spec/integration/use_cases/accounts/apps/chatwoots/webhooks/events/message/message_spec.rb
> +      end
Acho que esta maneiro, só adicionaria mais um caso de erro:
Quando o arquivo estiver sem acesso/corrompido

2024-02-28 10:38 UTC, douglara requested changes

2024-02-28 10:38 UTC, douglara commented on spec/models/attachment_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Aqui como ainda não tem testes da para deletar

2024-02-29 23:29 UTC, YukioArie commented on app/models/attachment.rb
> +                    contact: 8 }
Boa ideia

2024-03-01 10:40 UTC, douglara requested changes

2024-03-01 10:40 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      done_at: webhook['created_at'].to_time + 1.seconds,
Aqui temos que manter as datas iguais. O caso da ordenação podemos fazer alguma medida para contornar desde que não altere o comportamento dos outros eventos

2024-03-01 10:40 UTC, douglara commented on config/environments/development.rb
> +  config.action_controller.default_url_options = { host: 'http://127.0.0.1', port: 3001 }
Esses valores bora puxar via variável de ambiente.
Talvez seja necessário colocar em produção também

2024-03-01 10:40 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_attachments.rb
> +class Accounts::Apps::Chatwoots::Webhooks::ImportAttachments
Esse caso de uso faz: Importa os arquivos pulando o primeiro.
É interessante colocarmos algo sobre isso para ficar mais explícito o que é feito

2024-03-01 11:28 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_attachments.rb
> +class Accounts::Apps::Chatwoots::Webhooks::ImportAttachments
Bom ponto!

2024-03-01 11:42 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      done_at: webhook['created_at'].to_time + 1.seconds,
Segue um exemplo:

```ruby
  def self.build_done_at(webhook)
    if webhook['attachments'].present?
      webhook['created_at'].to_time + miliseconds(1)
    else
      webhook['created_at'].to_time
    end
  end

  def self.miliseconds(miliseconds)
    miliseconds/1000.0
  end
```

2024-03-01 17:06 UTC, YukioArie commented on config/environments/development.rb
> +  config.action_controller.default_url_options = { host: 'http://127.0.0.1', port: 3001 }
Boa!

2024-03-01 17:30 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      done_at: webhook['created_at'].to_time + 1.seconds,
Boa!

2024-03-04 11:44 UTC, douglara requested changes

2024-03-04 11:44 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      '? <@ additional_attributes', { chatwoot_id: webhook['conversation']['messages'].first['id'] }.to_json
```suggestion
      ''? <@ additional_attributes', { chatwoot_id: webhook['id'] }.to_json
```

Aqui a forma antiga não seria melhor?

2024-03-04 11:44 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      webhook['created_at'].to_time + miliseconds(1)
Hmmm aqui não acho interessante alterar o objeto `webhook` isso pode causar efeitos colaterais difícil de detectar

2024-03-04 11:44 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
>        content: webhook['content'],
Esse trecho aqui esta duplicado, talvez de para criar um caso de uso para fazer o build do evento

2024-03-04 11:44 UTC, douglara commented on config/environments/development.rb
> +  config.action_controller.default_url_options = { host: 'http://127.0.0.1', port: 3001 }
Hmmm tava em dúvida como ficaria em prod mas parece tudo certo, pode ser esse trecho que esteja te atrapalhando

![image](https://github.com/douglara/woofed-crm/assets/14988496/c4d83578-345f-4ddb-b52e-216b7e7eb32f)

![image](https://github.com/douglara/woofed-crm/assets/14988496/db55c2a3-7ad5-48ee-ac52-d37f1ec6f84d)

2024-03-04 11:44 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_attachments_skip_first.rb
> +                             filename: "attachment_#{attachment_params['file_type']}_#{event.additional_attributes['chatwoot_id']}")
Campos para preencher

```ruby
  filename: 'file.pdf',
  content_type: 'application/pdf',
````

2024-03-04 19:43 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      '? <@ additional_attributes', { chatwoot_id: webhook['conversation']['messages'].first['id'] }.to_json
Eu fiz essa alteração para a gnt n ter dúvidas se ele está pegando o id correto, pois a gnt recebe um webhook com vários ids, e teve um caso  q eu reparei q estava puxando o id errado de um outro caso.

2024-03-04 19:46 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      webhook['created_at'].to_time + miliseconds(1)
Boa observação!

2024-03-04 19:54 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
>        content: webhook['content'],
Sim, mas no import attachment ele n tem esse trecho:
```ruby
 done_at: build_done_at(webhook),
``` 
O dele, ele cria com o `webhook['created_at']` sem passar por `build_done_at(webhook)`. Por isso q eu acabei deixando separado esse método de buildar o evento.

2024-03-04 21:34 UTC, YukioArie commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_attachments_skip_first.rb
> +                             filename: "attachment_#{attachment_params['file_type']}_#{event.additional_attributes['chatwoot_id']}")
O content_type n é necessário utilizar

2024-03-04 22:15 UTC, douglara commented on app/use_cases/accounts/apps/chatwoots/webhooks/import_message.rb
> +      '? <@ additional_attributes', { chatwoot_id: webhook['conversation']['messages'].first['id'] }.to_json
Entendi
Mas esse caso que você pegou com erro será que não pode ter sido nesse arquivo? `app/use_cases/accounts/apps/chatwoots/webhooks/process_webhook.rb`

2024-03-05 19:55 UTC, douglara requested changes

2024-03-05 19:55 UTC, douglara commented on config/application.rb
> +    end
Essa config esta duplicada no caso de produção e dev

2024-03-05 20:13 UTC, douglara commented on config/application.rb
> +    end
Unifiquei nesse commit
https://github.com/douglara/woofed-crm/pull/258/commits/5442b5501832b2a2d69f19d754c8f51a677a0c79

2024-03-05 20:21 UTC, merged

2024-03-05 21:10 UTC, YukioArie commented on config/application.rb
> +    end
@douglara, pior que n tá. O q está no development e production é para solucionar o caso de quando a gnt faz um broadcast do attachment e ele n renderiza, somente usando o `config.action_controller.default_url_options` esse problema é resolvido. O q tem no application é o ` Rails.application.routes.default_url_options` e usando somente esse trecho, a gnt n consegue resolver o problema do broadcast