Fix custom attribute definitions bugs
douglara/woofed-crm pull request #262
Opened 2024-02-22 17:54 UTC by YukioArie

2024-04-11 20:05 UTC, douglara requested changes

2024-04-11 20:05 UTC, douglara commented on app/models/concerns/custom_attribute_definition/broadcastable.rb
> +      broadcast_append_later_to "custom_attributes_definitions_#{self.account.id}", target: 'custom_attributes_definitions', partial: 'accounts/settings/custom_attributes_definitions/custom_attribute
Aqui tava pensando de padronizarmos talvez algo como:

```suggestion
      broadcast_append_later_to [self.account, self], target: 'custom_attributes_definitions', partial: 'accounts/settings/custom_attributes_definitions/custom_attribute_definition', locals: {custom_attributes_definition: self}
```

2024-04-21 20:06 UTC, YukioArie commented on app/models/concerns/custom_attribute_definition/broadcastable.rb
> +      broadcast_append_later_to "custom_attributes_definitions_#{self.account.id}", target: 'custom_attributes_definitions', partial: 'accounts/settings/custom_attributes_definitions/custom_attribute
Testei dessa forma e não funcionou, pq o canal que irá escutar esse broadcast, será um canal global, e precisamos que esse broadcast faça referencia a esse canal global. Pelo que eu entendi, quando colocamos o self, ele varia o valor dependendo da ação em que ele irá ser executado. Para simplificar e deixar padronizado, eu optei por deixa-lo dessa forma [account, :custom_attribute_definition], agora irá sempre se comunicar com o canal que tenha o mesmo account e q tenha o :custom_attribute_definition, o :custom_attribute_definition por ser global, n terá o problema q estava ocorrendo quando eu testei com o self. FIcou assim: 
```ruby
module CustomAttributeDefinition::Broadcastable
  extend ActiveSupport::Concern
  included do
    after_create_commit do
      broadcast_append_later_to [account, :custom_attribute_definition],
                                target: 'custom_attributes_definitions', partial: 'accounts/settings/custom_attributes_definitions/custom_attribute_definition', locals: { custom_attributes_definition: self }
    end
    after_update_commit do
      broadcast_replace_later_to [account, :custom_attribute_definition], target: self,
                                                                          partial: 'accounts/settings/custom_attributes_definitions/custom_attribute_definition', locals: { custom_attributes_definition: self }
    end
    after_destroy_commit do
      broadcast_remove_to [account, :custom_attribute_definition], target: self
    end
  end
end
``` 
E no index ficou assim: 
```ruby
<%= turbo_stream_from [current_user.account, :custom_attribute_definition] %>
```

2024-04-21 21:01 UTC, YukioArie commented
@douglara, aqui n ta funcionando a migração de correção desse pull request, q tem aquele bug q n deixa criar um custom attribute com a mesma key em contas diferentes, lembro q quando criei esse pull request, tinha resolvido esse problema. Acredito q seja problema de migração, mas testa na sua maquina tbm, mt estranho

2024-04-22 17:37 UTC, YukioArie commented
@douglara, testei novamente na minha maquina, e agora foi. Antes n estava indo pq provavelmente eu estava rodando outros processos nele

2024-04-24 10:37 UTC, douglara approved these changes

2024-04-24 10:39 UTC, douglara commented on db/schema.rb
> +  end
Quando tem migração só ficar de olho para ver se não esta pegando coisas do banco local 🙂

2024-04-24 10:59 UTC, merged

2024-04-24 11:06 UTC, YukioArie commented on db/schema.rb
> +  end
Boa!!! Esqueci desse detalhe 😄