Add attachment front end
douglara/woofed-crm pull request #268
Opened 2024-03-05 21:12 UTC by YukioArie

2024-03-07 19:42 UTC, douglara requested changes

2024-03-07 19:42 UTC, douglara commented on app/javascript/controllers/teste.html
> +          <audio controls>
Esse arquivo acho que foi por engano

2024-03-07 19:42 UTC, douglara commented on app/models/event.rb
> +    attachment.image? || attachment.file? || attachment.video? if attachment.present?
O que acha?

```suggestion
    attachment.present? && ( attachment.image? || attachment.file? || attachment.video? )
```

2024-03-07 19:42 UTC, douglara commented on app/views/accounts/contacts/events/_attachment.html.erb
> +<% if event.attachment.present? %>
Se mover esse if para onde chama essa partial?

2024-03-07 19:42 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +      <%= render 'accounts/contacts/events/attachment', event: event %>
```suggestion
      <%= render 'accounts/contacts/events/attachment', event: event if event.attachment.present? %>
```

2024-03-07 19:42 UTC, douglara commented on app/assets/stylesheets/application.scss
> +}
Esses aqui quero dar uma olhada com mais calma

2024-03-08 04:46 UTC, YukioArie commented on app/javascript/controllers/teste.html
> +          <audio controls>
No meio de vários arquivos 'stasheados' esse acabou entrando junto 😄

2024-03-08 04:51 UTC, YukioArie commented on app/models/event.rb
> +    attachment.image? || attachment.file? || attachment.video? if attachment.present?
Ótima ideia! Do jeito que eu fiz se n tiver media_attachment, ele retornará nil. Do jeito que vc fez ele retornará true ou false, que é o comportamento mais adequado.

2024-03-08 04:56 UTC, YukioArie commented on app/views/accounts/contacts/events/_attachment.html.erb
> +<% if event.attachment.present? %>
Boa ideia!

2024-03-08 04:57 UTC, YukioArie commented on app/views/accounts/contacts/events/_event.html.erb
> +      <%= render 'accounts/contacts/events/attachment', event: event %>
Boa! Fica mais intuitivo chamando esse if ao renderizar a partial.

2024-03-08 05:04 UTC, YukioArie commented on app/assets/stylesheets/application.scss
> +}
Como eu n conseguia acessar a tag trix, pois o html trix é renderizado dinamicamente, eu n consegui alterar o estilo dele usando classes de tailwind. Logo, tive que alterar usando css padrão msm para ficar com o estilo do figma. O trecho: 
```ruby
.trix-button-group.trix-button-group--file-tools {
  display:none;
}
``` 
É para remover o botão de arquivos do trix.

O estilo antes e depois ao eu alterar o css trix: 

# Estilo atual: 

![image](https://github.com/douglara/woofed-crm/assets/45243355/5c8ddf80-b8ce-45e1-b4dd-b3f0dd939fff)

# Estilo com o css que eu adicionei: 

![image](https://github.com/douglara/woofed-crm/assets/45243355/19935a79-bca0-43f1-9d14-647826b9579b)

2024-03-12 01:50 UTC, douglara approved these changes

2024-03-12 01:51 UTC, merged