Add upload attachment form
douglara/woofed-crm pull request #270
Opened 2024-03-13 05:51 UTC by YukioArie

2024-03-26 01:57 UTC, douglara requested changes

2024-03-26 01:57 UTC, douglara commented on app/views/components/events/form/_attachments.html.erb
> +<div class="border-t border-light-palette-p3 p-3 mt-4 space-y-2" data-controller="upload-files" data-upload-files-xmark-svg-url-value="<%= asset_path('xmark-solid.svg') %>" >
Aqui não é melhor utilizar o lucide?
https://lucide.dev/icons/x

2024-03-26 01:57 UTC, douglara commented on app/models/event.rb
> +    return false if invalid?
Será que precisa disso?
Imagino que no super deve fazer essa checagem

2024-03-26 01:57 UTC, douglara commented on app/use_cases/accounts/contacts/events/create.rb
> +        { ok: event }
Esse aqui foi descontinuado né?

2024-03-26 01:57 UTC, douglara commented on app/views/components/events/form/_attachments.html.erb
> +      <%# form.file_field :files, multiple: true, direct_upload: true, class: 'hidden', data: {"upload-files-target": "fileInput", action:'change->upload-files#acceptFiles'} %>
Hmmm talvez para utilizar dessa forma precisa passar o event

2024-03-26 01:57 UTC, douglara commented on app/views/components/events/form/_chatwoot_message.html.erb
> +  <%= form.hidden_field :contact_id %>
Aqui esta pendente adicionar o:
`<%= render 'components/events/form/attachments', form: form %>`

2024-03-26 11:34 UTC, YukioArie commented on app/models/event.rb
> +    return false if invalid?
Resolvido!

2024-03-26 11:40 UTC, YukioArie commented on app/views/components/events/form/_attachments.html.erb
> +      <%# form.file_field :files, multiple: true, direct_upload: true, class: 'hidden', data: {"upload-files-target": "fileInput", action:'change->upload-files#acceptFiles'} %>
Resolvido!

2024-03-28 10:43 UTC, YukioArie commented on app/use_cases/accounts/contacts/events/create.rb
> +        { ok: event }
Isso msm.

2024-04-11 19:51 UTC, douglara requested changes

2024-04-11 19:51 UTC, douglara commented on app/models/event.rb
> +  end
Hmmm não achei que precisária desse método aqui
Pelo que entendi esta sendo utilizado para enviar para o Chatwoot, não seria mais simples fazer direto?

2024-04-11 19:51 UTC, douglara commented on spec/controllers/accounts/contacts/events_controller_spec.rb
> +
```suggestion
```

2024-04-11 20:28 UTC, YukioArie commented on app/models/event.rb
> +  end
N, pq quando implementarmos o envio de arquivos no evolution, será necessário usar esse metodo. Por isso q eu criei no model, para n haver duplicação

2024-04-15 23:57 UTC, merged