Add hotwire to events forms
douglara/woofed-crm pull request #275
Opened 2024-03-19 07:23 UTC by YukioArie

2024-03-20 11:15 UTC, douglara requested changes

2024-03-20 11:15 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
>      end
Isso aqui agora da para remover

2024-03-20 11:15 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    @event = EventBuilder.new(current_user, event_params.merge({ contact: @contact })).build
Aqui não teria que ser o contact_id?

2024-03-20 11:15 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +        end
Hmmm agora daria para remover isso aqui né?

2024-03-20 11:15 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    @event = Event.find(params[:id])
```suggestion
    @event = current_user.account.events.find(params[:id])
```

2024-03-20 11:15 UTC, douglara commented on app/controllers/accounts/contacts/events_controller.rb
> +    @contact = Contact.find(params[:contact_id])
```suggestion
    @contact = current_user.contacts..find(params[:contact_id])
```

2024-03-20 11:45 UTC, YukioArie commented on app/controllers/accounts/contacts/events_controller.rb
> +    @event = EventBuilder.new(current_user, event_params.merge({ contact: @contact })).build
N precisa.

2024-03-20 11:47 UTC, YukioArie commented on app/controllers/accounts/contacts/events_controller.rb
> +        end
Acho melhor deixar ele.

2024-03-20 12:07 UTC, YukioArie commented on app/controllers/accounts/contacts/events_controller.rb
> +    @event = Event.find(params[:id])
Boa!

2024-03-20 12:09 UTC, YukioArie commented on app/controllers/accounts/contacts/events_controller.rb
> +    @contact = Contact.find(params[:contact_id])
Showw! Fiz o ajuste assim: 
```ruby
@contact = current_user.account.contacts.find(params[:contact_id])
```

2024-03-21 01:41 UTC, douglara approved these changes

2024-03-21 01:41 UTC, douglara commented on app/views/accounts/contacts/events/new.html.erb
> +  turbo_frame_id: dom_id(@event),
Esse parâmetro não da para remover?
Ai lá no 
app/views/components/events/_form.html.erb
Substitituir a linha:
`<%= turbo_frame_tag turbo_frame_id do %>`
por:
`<%= turbo_frame_tag event do %>`

2024-03-21 01:41 UTC, douglara commented on app/views/accounts/contacts/events/new.html.erb
> +  header_chatwoot_message_url: new_account_contact_event_path(@event.account, @event.contact, kind: 'chatwoot_message', pipeline: @event.deal.pipeline, deal_id: @event.deal.id)
Hmmm isso aqui não sei mas bora ver em um próximo card heheh
Já esta bem maneiro a refatoração

2024-03-21 01:42 UTC, merged