Add pagination to events using turbo frames
douglara/woofed-crm pull request #282
Opened 2024-04-06 20:12 UTC by YukioArie

2024-04-10 11:02 UTC, douglara requested changes

2024-04-10 11:02 UTC, douglara commented on app/views/accounts/deals/events_done.turbo_stream.erb
> +  <%= turbo_stream.remove :pagination %>
Hmmm esse remove pagination acaba removendo todos da página ai quando atingimos o máximo de um scroll os outros da página são afetados também

2024-04-11 05:14 UTC, YukioArie commented on app/views/accounts/deals/events_done.turbo_stream.erb
> +  <%= turbo_stream.remove :pagination %>
Acabei de corrigir 😃, agora tá 💯 !

2024-04-11 12:14 UTC, douglara approved these changes

2024-04-11 12:14 UTC, douglara commented on app/models/concerns/deal/broadcastable.rb
> +                                                         partial: 'accounts/contacts/events/events_done', locals: { deal: deal, events: events_done, pagy: 1 }
Esse aqui não sei se esta certo hehe mas bora seguir e vemos mais a frente

2024-04-11 12:17 UTC, douglara requested changes
Opaa só atualizar os testes

2024-04-11 12:42 UTC, YukioArie commented
> Opaa só atualizar os testes

Acabei esquecendo desse detalher hehe 😅

2024-04-11 12:44 UTC, YukioArie commented on app/models/concerns/deal/broadcastable.rb
> +                                                         partial: 'accounts/contacts/events/events_done', locals: { deal: deal, events: events_done, pagy: 1 }
🤔

2024-04-11 12:46 UTC, merged