Add crud product backend
douglara/woofed-crm pull request #302
Opened 2024-04-19 19:21 UTC by YukioArie

2024-04-20 16:30 UTC, douglara requested changes

2024-04-20 16:30 UTC, douglara commented on db/migrate/20240419183543_create_products.rb
> +      t.string :description, null: false, default: ''
Hmmmm aqui talvez seja melhor utilizar text por ser maior

2024-04-22 21:20 UTC, YukioArie commented on db/migrate/20240419183543_create_products.rb
> +      t.string :description, null: false, default: ''
Fiz uma pesquisa aqui, e vc tem razão. Nesse caso por ser um campo que pode ser grande, o ideal é armazenar no db como TEXT msm. Fiz a alteração desse campo tbm no crawler

2024-04-22 21:34 UTC, YukioArie commented on db/migrate/20240419183543_create_products.rb
> +      t.string :description, null: false, default: ''
Aliás, n seria interessante fazer parecido com a implementação dos eventos? Onde o conteudo quem cuida é o trix

2024-04-23 11:22 UTC, merged