Add products frontend
douglara/woofed-crm pull request #308
Opened 2024-04-24 06:14 UTC by YukioArie

2024-04-29 21:40 UTC, douglara requested changes

2024-04-29 21:40 UTC, douglara commented on app/controllers/accounts/products_controller.rb
> +    # @product = current_user.account.products.new(product_params)
```suggestion
```

2024-04-29 21:40 UTC, douglara commented on app/views/accounts/products/index.html.erb
> +<%# 25.times{ |index| Product.create(name: "produto #{index}", identifier: "LFD#{index}ADSSA", quantity_available: 10, description: "Descrição #{index}", amount: "1#{index}00".to_i)} %>
```suggestion

```

2024-04-29 21:40 UTC, douglara commented on app/views/accounts/products/index.html.erb
> +<section class="m-8 bg-light-palette-p5 border-2 border-light-palette-p3 rounded-md ">
Aqui dar uma corrigida na indentação

2024-04-29 21:40 UTC, douglara commented on spec/controllers/accounts/products_controller_spec.rb
> +        end
Para facilitar a leitura =)

```suggestion
        end

```

2024-04-29 21:40 UTC, douglara commented on spec/controllers/accounts/products_controller_spec.rb
> +  end
```suggestion
  end

```

2024-04-29 21:40 UTC, douglara commented on spec/factories/products.rb
> +    additional_attributes { '' }
```suggestion
    custom_attributes { {} }
    additional_attributes { {} }
```

2024-04-29 21:40 UTC, douglara commented on app/views/accounts/products/_product.html.erb
> +        <i data-lucide="image" class='w-[50px] h-[50px] lg:w-[65px] lg:h-[65px] p-4 stroke-dark-gray-palette-p3'></i>
Esse ícone aqui ta ficando distorcido hehe

![image](https://github.com/douglara/woofed-crm/assets/14988496/4c8a96ea-6471-49f6-b19a-95fd4d82e729)


Segue uma sugestão de código:

```ruby
      <div class="border-2 bg-brand-palette-08 rounded-md h-16 w-16 flex items-center">
        <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
      </div>

```

![image](https://github.com/douglara/woofed-crm/assets/14988496/14f08f15-4f54-4dd2-995e-69d130b74c2f)

2024-04-29 21:40 UTC, douglara commented on app/models/product.rb
> +    amount = amount.gsub(/[^\d-]/, '').to_i if amount.is_a?(String)
Boaa!

2024-04-30 02:05 UTC, YukioArie commented on app/views/accounts/products/index.html.erb
> +<section class="m-8 bg-light-palette-p5 border-2 border-light-palette-p3 rounded-md ">
Esse codigo já está indentado 😃

2024-04-30 02:06 UTC, YukioArie commented on app/views/accounts/products/index.html.erb
> +<%# 25.times{ |index| Product.create(name: "produto #{index}", identifier: "LFD#{index}ADSSA", quantity_available: 10, description: "Descrição #{index}", amount: "1#{index}00".to_i)} %>
Acabei esquecendo de remover 😄

2024-04-30 02:07 UTC, YukioArie commented on spec/controllers/accounts/products_controller_spec.rb
> +        end
Boa!

2024-04-30 04:32 UTC, YukioArie commented on app/views/accounts/products/_product.html.erb
> +        <i data-lucide="image" class='w-[50px] h-[50px] lg:w-[65px] lg:h-[65px] p-4 stroke-dark-gray-palette-p3'></i>
Tens razão, acabou que nem percebi hehe. Mas n é legal mesmo mudar o tamanho, pq dependendo do svg, pq ele acaba 'quebrando'. Testei a sua solução, e funcionou perfeitamente.

2024-05-02 06:14 UTC, douglara commented on app/views/accounts/products/index.html.erb
> +<section class="m-8 bg-light-palette-p5 border-2 border-light-palette-p3 rounded-md ">
Heheh verdade foi mals 😆

2024-05-02 06:28 UTC, merged