Add support send attachments to evolutionapi
douglara/woofed-crm pull request #311
Opened 2024-04-30 01:47 UTC by YukioArie

2024-05-04 00:01 UTC, douglara requested changes

2024-05-04 00:01 UTC, douglara commented on app/use_cases/accounts/apps/evolution_apis/message/delivery_job.rb
> +                                                                @event).call
Aqui talvez passar direto o evento fica melhor ex:

```suggestion
      result = Accounts::Apps::EvolutionApis::Message::Send.new(@event).call
```

2024-05-04 00:01 UTC, douglara commented on app/use_cases/accounts/apps/evolution_apis/message/delivery_job.rb
> +        @event.additional_attributes.merge!({ 'message_id' => result[:ok]['key']['id'] })
Se tiveres outros valores no `additional_attributes` será que limpa?

2024-05-04 00:01 UTC, douglara commented on spec/integration/use_cases/accounts/apps/evolution_apis/message/delivery_job_spec.rb
> +  describe 'failed' do
```suggestion
  end

  describe 'failed' do
```

2024-05-04 00:01 UTC, douglara commented on spec/integration/use_cases/accounts/apps/evolution_apis/message/delivery_job_spec.rb
> +    context 'send message' do
```suggestion
    end

    context 'send message' do
```

2024-05-04 02:13 UTC, YukioArie commented on app/use_cases/accounts/apps/evolution_apis/message/delivery_job.rb
> +                                                                @event).call
Consegui remover o @event.app, mas o `phone_id` eu n vi outro jeito de pegar ele a n ser por parametro.
Ficou assim: 
```ruby
result = Accounts::Apps::EvolutionApis::Message::Send.new(@event).call
```

2024-05-04 02:38 UTC, YukioArie commented on app/use_cases/accounts/apps/evolution_apis/message/delivery_job.rb
> +        @event.additional_attributes.merge!({ 'message_id' => result[:ok]['key']['id'] })
Nop, o `merge!`  faz o merge da hash passada no parametro, e se a key dessa hash existir, ele irá substituir o value. Ex: 
```ruby
irb(main):006> e.additional_attributes
=> {"teste1"=>"1", "teste2"=>"teste2", "message_id"=>"1"}
irb(main):007> e.additional_attributes.merge!({ 'message_id_2' => '2' })
=> {"teste1"=>"1", "teste2"=>"teste2", "message_id"=>"1", "message_id_2"=>"2"}
irb(main):008> e.additional_attributes.merge!({ 'message_id_2' => '150' })
=> {"teste1"=>"1", "teste2"=>"teste2", "message_id"=>"1", "message_id_2"=>"150"}
```

2024-05-07 03:22 UTC, douglara requested changes

2024-05-07 03:22 UTC, douglara commented on app/use_cases/accounts/apps/evolution_apis/message/send.rb
> +    @evolution_api = event.account.apps_evolution_apis.first
Esse `.first` pode causar problemas pois é possível ter várias conexões da Evolution.
O evento tem um relacionamento direto com a app que ele pertence seria: `event.app`

2024-05-07 03:22 UTC, douglara commented on app/use_cases/accounts/apps/evolution_apis/message/send.rb
> +    file_url = Rails.application.routes.url_helpers.rails_blob_url(@event.attachment.file)
Acho que ficaria bom um método para retonar a url do attachment
Achei esse exmplo do Chatwoot interessante:
https://github.com/chatwoot/chatwoot/blob/4c1c856562a6b69649e5db416b1e0ea717c24a34/app/models/attachment.rb#L59

2024-05-07 13:09 UTC, YukioArie commented on app/use_cases/accounts/apps/evolution_apis/message/send.rb
> +    @evolution_api = event.account.apps_evolution_apis.first
Boa! Esse caso é um problema msm

2024-05-07 14:32 UTC, YukioArie commented on app/use_cases/accounts/apps/evolution_apis/message/send.rb
> +    file_url = Rails.application.routes.url_helpers.rails_blob_url(@event.attachment.file)
Boa, extrai esse trecho `Rails.application.routes.url_helpers.rails_blob_url(@event.attachment.file)` para um método em attachments chamado `download_url`. Ficou assim: 
```ruby
  def download_url
    file.attached? ? Rails.application.routes.url_helpers.rails_blob_url(file) : ''
  end
``` 
Tentei fazer parecido com relação a implementação do chatwoot, mas por algum motivo, o `file.blob.url` n está funcionando, acredito que seja erro ou incompatibilidade nas configs no active storage. o erro q ta dando é esse: 
```ruby
file.blob.url
eval error: bad URI(is not URI?): nil
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/lib/active_storage/service/disk_service.rb:127:in `generate_url'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/lib/active_storage/service/disk_service.rb:107:in `private_url'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/lib/active_storage/service.rb:118:in `block in url'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/lib/active_storage/service.rb:155:in `instrument'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/lib/active_storage/service.rb:113:in `url'
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.7.7/app/models/active_storage/blob.rb:199:in `url'
  (rdbg)//home/yukioarie/woofed-crm/app/models/attachment.rb:1:in `download_url'
``` 
E eu n implementei esse trecho: `ActiveStorage::Current.url_options = Rails.application.routes.default_url_options if ActiveStorage::Current.url_options.blank?` q tem no metodo do chatwoot, pq estava retornando erro:
```ruby
ActiveStorage::Current.url_options
eval error: undefined method `url_options' for #<ActiveStorage::Current:0x000055f3dddd44c0 @attributes={}>
  /home/yukioarie/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/current_attributes.rb:163:in `url_options'
  (rdbg)//home/yukioarie/woofed-crm/app/models/attachment.rb:1:in `download_url'
``` 
Daí eu n adicionei esse trecho, até pq n vi necessidade em adicioná-lo.

2024-05-08 09:24 UTC, douglara approved these changes

2024-05-08 09:25 UTC, merged