Add image product frontend
douglara/woofed-crm pull request #314
Opened 2024-05-03 06:18 UTC by YukioArie

2024-05-07 10:55 UTC, douglara requested changes

2024-05-07 10:55 UTC, douglara commented on app/views/components/products/_images_carousel_list.html.erb
> +    <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
Aqui esta tendo uma quebra de layout quando tem e não tem imagens

![image](https://github.com/douglara/woofed-crm/assets/14988496/3d8eba59-2ba1-47d2-b79e-8dabe107aa46)

2024-05-07 10:55 UTC, douglara commented on app/views/accounts/products/_attachment_fields.html.erb
> +<div class='nested-fields' data-controller="load-lucid-icons">
Bora seguir nessa ideia mas acho que é importante puxarmos logo um dropzone/fileupload maneiro para manter a boa experiência
Talvez podemos fazer algo nessa linha:
https://www.youtube.com/watch?v=7JNRZLTRDCc

2024-05-08 01:24 UTC, YukioArie commented on app/views/components/products/_images_carousel_list.html.erb
> +    <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
Boa observação! Fiz a correção e ficou assim: 

![image](https://github.com/douglara/woofed-crm/assets/45243355/0d0b33d3-5e89-4fdf-8410-beb16eadaa3d)

2024-05-08 01:24 UTC, YukioArie commented on app/views/accounts/products/_attachment_fields.html.erb
> +<div class='nested-fields' data-controller="load-lucid-icons">
Boa! Vamos puchar nesse proximo sprint mesmo. Essa funcionalidade vai dar trabalho, rs/

2024-05-08 09:55 UTC, douglara commented on app/views/components/products/_images_carousel_list.html.erb
> +    <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
Hmmm acho que ainda ficou um quebra de alinhamentos

Talvez algo assim:
![image](https://github.com/douglara/woofed-crm/assets/14988496/fe6dfb8a-a56e-41d3-86fc-b2274b174d46)

O bloco da imagem sempre ser quadrado com um h e w igual.
No caso da imagem que não tem as setinhas talvez seja necessário colocar uma div ou margin para preencher o espaço.

2024-05-08 09:57 UTC, douglara requested changes

2024-05-08 09:57 UTC, douglara commented on app/views/accounts/products/_product.html.erb
> +    <%= render '/components/products/images_carousel_list', product: product, height: 24 %>
Aqui estava pensando de em vez de passar o parâmetros height, o elemento pai configura os limites por exemplo na div a cima com um h-24
E a partial ocupa o espaço que ela tem disponível

2024-05-08 11:27 UTC, douglara commented on app/views/components/products/_images_carousel_list.html.erb
> +    <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
![image 6](https://github.com/douglara/woofed-crm/assets/14988496/9e745886-9b86-4863-a21e-f49f6a11f100)

2024-05-08 12:26 UTC, YukioArie commented on app/views/accounts/products/_product.html.erb
> +    <%= render '/components/products/images_carousel_list', product: product, height: 24 %>
Boa ideia, acabei de fazer essa alteração.

2024-05-08 12:30 UTC, YukioArie commented on app/views/components/products/_images_carousel_list.html.erb
> +    <i data-lucide="image" class='stroke-dark-gray-palette-p4 m-auto'></i>
Boa! Fiz alguns ajustes, e ficou assim: 

![image](https://github.com/douglara/woofed-crm/assets/45243355/e998ba61-3e5e-46e7-8d18-0f9d780c5209)

Agora ambas imagens estão com o mesmo width e height:

![image](https://github.com/douglara/woofed-crm/assets/45243355/d72aaff7-3ac3-4791-8995-f9ed4641a243)

![image](https://github.com/douglara/woofed-crm/assets/45243355/22caa537-c554-441f-a1a5-9ca2cde21424)

2024-05-12 00:34 UTC, douglara approved these changes

2024-05-12 00:34 UTC, merged