Add product to deal
douglara/woofed-crm pull request #322
Opened 2024-05-12 03:11 UTC by YukioArie

2024-05-15 23:13 UTC, douglara requested changes

2024-05-15 23:13 UTC, douglara commented on app/models/account.rb
> +  has_many :deal_products
```suggestion
  has_many :deal_products, dependent: :destroy
```

Para quando deletarmos a conta deletar esses relacionamentos também

2024-05-15 23:13 UTC, douglara commented on app/models/deal.rb
> +  has_many :deal_products
```suggestion
  has_many :deal_products, dependent: :destroy
```

2024-05-15 23:13 UTC, douglara commented on app/views/accounts/deals/_details.html.erb
>      <div class="p-1 bg-light-palette-p5 min-[1400px]:rounded-b-md border-x-2 border-b-2 border-light-palette-p3">
Aqui da para ajustarmos a borda para ficar reta hehe

![image](https://github.com/douglara/woofed-crm/assets/14988496/b893f2b4-7be2-47b0-8033-e54720610147)

2024-05-15 23:13 UTC, douglara commented on app/models/concerns/deal_product/broadcastable.rb
> +      broadcast_remove_to [account.id, :deal], target: self
Só de curiosidade heheh

https://github.com/hotwired/turbo-rails/issues/506

2024-05-17 10:57 UTC, douglara requested changes

2024-05-17 10:57 UTC, douglara commented on app/controllers/accounts/products_controller.rb
> +    @deal_product = nil
Não entenbi bem o porque desse `@deal_product = nil`
Não deveria sempre encontrar um deal_product?

2024-05-17 10:57 UTC, douglara commented on app/controllers/accounts/products_controller.rb
> +  before_action :set_deal_product, only: %i[edit update]
```suggestion
  before_action :set_deal_product, only: %i[edit update]

```

2024-05-17 10:57 UTC, douglara commented on app/views/accounts/deal_products/destroy.turbo_stream.erb
> +<%= turbo_stream.replace :notification do %>
Aqui será que não vai mostrar essa notificação para todos os usuários?

2024-05-17 10:57 UTC, douglara commented on app/views/accounts/deals/details/_edit.html.erb
> +    <%= form.hidden_field :deal_page_id, value: params[:deal_page_id] %>
Essa váriavel `deal_page_id`, será que não fica melhor chamar de `deal_id`?

2024-05-20 10:38 UTC, douglara requested changes

2024-05-20 10:38 UTC, douglara commented on app/views/components/_notifications.html.erb
> +
```suggestion
```

2024-05-20 10:38 UTC, douglara commented on app/views/components/_notifications.html.erb
> +<%= turbo_frame_tag :notification do %>
```suggestion
<%= turbo_frame_tag :flash_message do %>
```

Será que utilizar `flash` para não misturar com a implementação de notificação?

2024-05-20 10:38 UTC, douglara commented on app/controllers/accounts/deals_controller.rb
> +
Aquele ponto da action ter dois comportamentos uma para o `product` e outra para o `deal_product` podemos ou colocar nesse controller do `deal` ou no controller `deal_product`

2024-05-20 20:30 UTC, YukioArie commented on app/views/components/_notifications.html.erb
> +<%= turbo_frame_tag :notification do %>
Boa ideia!

2024-05-20 20:36 UTC, YukioArie commented on app/controllers/accounts/deals_controller.rb
> +
Acho interessante deixar no `deal` msm, pq nesse caso ele vai exibir o deal_product somente na pagina do `deal`. Igual a logica dos events. As duas actions de listagem dos eventos, `events_to_do` e `events_done`, estão no deal, e n no controller `events`, pq a listagem desses eventos estão sendo renderizados na pagina do deal.

2024-05-21 03:47 UTC, YukioArie commented on app/views/accounts/deals/details/_edit.html.erb
> +    <%= form.hidden_field :deal_page_id, value: params[:deal_page_id] %>
Tbm acho, mas o problema desse parametro é q ele está sendo usando em outros forms e em pelo menos 2 controllers diferentes. Acho melhor a gnt rever isso em um outro card.

2024-05-22 02:49 UTC, douglara approved these changes

2024-05-22 02:49 UTC, douglara commented on app/controllers/accounts/deals_controller.rb
> +  end
Dei um up aqui para evitar a duplicação

https://github.com/douglara/woofed-crm/pull/322/commits/12d686152233487d900f7aedb3977a5ef38647d9

2024-05-22 02:49 UTC, douglara commented on app/views/accounts/deals/edit_product.html.erb
> +  <%= turbo_frame_tag @deal_product do %>
```suggestion
<%= turbo_frame_tag @deal_product do %>
```

2024-05-22 02:49 UTC, douglara commented on app/views/components/_flash_message.html.erb
> +
```suggestion
```

2024-05-22 02:49 UTC, douglara commented on spec/controllers/accounts/deals_controller_spec.rb
> +          patch "/accounts/#{account.id}/deals/#{deal.id}/update_product?deal_product_id=#{deal_product.id}",
Masssa!

2024-05-22 02:55 UTC, merged