Add i18n to application
douglara/woofed-crm pull request #325
Opened 2024-05-15 03:49 UTC by YukioArie

2024-05-15 23:00 UTC, douglara requested changes

2024-05-15 23:00 UTC, douglara commented on config/initializers/i18n.rb
> +I18n.default_locale = 'es'
Aqui só puxar da váriavel de ambiente

2024-05-20 11:23 UTC, douglara requested changes

2024-05-20 11:23 UTC, douglara commented on .env.sample
> +LANGUAGE=LANGUAGE
```suggestion
LANGUAGE=en
```

2024-05-22 03:48 UTC, douglara requested changes

2024-05-22 03:48 UTC, douglara commented on app/controllers/accounts/apps/chatwoots_controller.rb
> +      redirect_to edit_account_apps_chatwoot_path(current_user.account, @chatwoot),
Bem massaa heim!

2024-05-22 03:48 UTC, douglara commented on config/locales/models/apps/chatwoot/pt-BR.yml
> +        chatwoot_endpoint_url: 'URL do endpoint chatwoot'
```suggestion
        chatwoot_endpoint_url: 'URL do Chatwoot'
```

2024-05-22 03:48 UTC, douglara commented on config/locales/models/apps/chatwoot/pt-BR.yml
> +        chatwoot_user_token: 'Token de usuário Chatwoot'
```suggestion
        chatwoot_user_token: 'Token de usuário do Chatwoot'
```

2024-05-22 03:48 UTC, douglara commented on config/locales/models/apps/chatwoot/en.yml
> +        chatwoot_endpoint_url: 'Chatwoot endpoint URL'
```suggestion
        chatwoot_endpoint_url: 'Chatwoot URL'
```

2024-05-22 03:48 UTC, douglara commented on app/views/accounts/deals/_form.html.erb
> +      <%= form.text_field :name, value: "#{t('views.accounts.deals.form.deal_with')} #{@deal.contact.full_name}", placeholder: "Negócio com João", class: 'form-input', required: 'true' %>
Heheh bem maneiro esse `views.accounts.deals.form.deal_with`
Faltou só o placeholder

2024-05-22 03:48 UTC, douglara commented on app/views/accounts/products/_product.html.erb
> +  <p class='w-[20%] typography-body-r-lh150 text-dark-gray-palette-p2 truncate'><%= l(product.created_at, format: :long) %></p>
Aqui não seria `t`?
```suggestion
  <p class='w-[20%] typography-body-r-lh150 text-dark-gray-palette-p2 truncate'><%= t(product.created_at, format: :long) %></p>
```

2024-05-22 03:48 UTC, douglara commented on app/views/accounts/settings/custom_attributes_definitions/_form.html.erb
> +      <%= form.text_field :attribute_display_name, placeholder: "CPF", class: 'form-input' %>
![image](https://github.com/douglara/woofed-crm/assets/14988496/484aa1d2-1c62-4abe-a6e4-a26474e95cd7)

🤣

2024-05-22 03:48 UTC, douglara commented on config/initializers/i18n.rb
> +I18n.default_locale = ENV['LANGUAGE']
Esse aqui é legal que já coloca um valor default caso não tenha nada no env
```suggestion
I18n.default_locale = ENV.fetch('LANGUAGE', 'en')
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/chatwoots/edit/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/evolution_apis/evolution_api/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/evolution_apis/form/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/evolution_apis/pair_qr_code/en.yml
> +            step_two: '2. Tap <b class="text-dark-gray-palette-p2">More options</b> on Android or <b class="text-dark-gray-palette-p2">Settings</b> on iPhone.'
O html será que rola legal?

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/evolution_apis/pair_qr_code/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/apps/evolution_apis/qrcode/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/contacts/events/event/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/contacts/events/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/contacts/form/pt-BR.yml
> +
```suggestion
```

2024-05-22 03:48 UTC, douglara commented on config/locales/views/accounts/deals/details/pt-BR.yml
> +
```suggestion
```

2024-05-23 18:22 UTC, YukioArie commented on app/views/accounts/products/_product.html.erb
> +  <p class='w-[20%] typography-body-r-lh150 text-dark-gray-palette-p2 truncate'><%= l(product.created_at, format: :long) %></p>
Nop, o l() é usado para datas, e o t() é usado para strings. Nesse caso eu estou fazendo 'tradução' de uma data e n uma string

2024-05-23 18:23 UTC, YukioArie commented on config/locales/views/accounts/apps/evolution_apis/pair_qr_code/en.yml
> +            step_two: '2. Tap <b class="text-dark-gray-palette-p2">More options</b> on Android or <b class="text-dark-gray-palette-p2">Settings</b> on iPhone.'
Sim, eu coloquei o .html_to_safe depois do t() na view.

2024-05-24 08:21 UTC, YukioArie commented on config/initializers/i18n.rb
> +I18n.default_locale = ENV['LANGUAGE']
Boa!

2024-05-24 17:54 UTC, merged

2025-11-12 02:55 UTC, YukioArie commented on .env.github
> +LANGUAGE=en
This line adds the LANGUAGE environment variable to set the system’s default translation. This is useful because if the translation ever needs to be changed, the application won’t have to be redeployed.

2025-11-12 03:25 UTC, YukioArie commented on app/models/contact.rb
> +       phone updated_at]
This change replaces a regular string array with the %w shorthand syntax. This is bad because it doesn’t follow the purpose of the PR.

2025-11-12 03:26 UTC, YukioArie commented on app/models/contact.rb
> +  after_commit :export_contact_to_chatwoot, on: %i[create update]
This change replaces a regular symbol array with the %i shorthand syntax. This is bad because it doesn’t follow the purpose of the PR.

2025-11-12 03:39 UTC, YukioArie commented on app/views/accounts/contacts/chatwoot_embed/_show.html.erb
This change removes the conditions that hide the email and phone fields when they don’t exist. This is bad because it doesn’t follow the purpose of the PR.

2025-11-12 03:43 UTC, YukioArie commented on app/views/accounts/contacts/_form.html.erb
> -
This change removes blank lines. This is good for improving code organization and consistency.