Convert navbar bootstrap to tailwind (#24)
douglara/woofed-crm pull request #33
Opened 2023-09-11 23:31 UTC by YukioArie

ref issue #24

2023-09-13 11:46 UTC, douglara requested changes
Boaa obrigado @YukioArie 😀

Segue alguns detalhes que eu verifiquei, qualquer dúvida ou sugestão pode mandar aqui mesmo

- [ ] Bordas
![image](https://github.com/douglara/woofed-crm/assets/14988496/06959f05-3614-4acb-9c42-d6ef26cd2e03)

![image](https://github.com/douglara/woofed-crm/assets/14988496/f665ad06-2eae-4980-b583-92369d828c82)


- [ ] Espaçamento

![image](https://github.com/douglara/woofed-crm/assets/14988496/15fc74f3-7469-4c88-91eb-a7da5e6000fd)


![image](https://github.com/douglara/woofed-crm/assets/14988496/2df1566c-28ec-482d-be2b-c4339260081c)

- [x] Verificar se o botão usa `font-semibold` ou `font-bold`

![image](https://github.com/douglara/woofed-crm/assets/14988496/a9cca30c-5ff0-4b9f-841d-1e0765a07fe5)


![image](https://github.com/douglara/woofed-crm/assets/14988496/6f052d94-52f2-4bb7-8f5d-472b198f3c29)

2023-09-13 11:46 UTC, douglara commented on app/views/layouts/shared/_navbar.html.erb
> +<nav class="flex flex-wrap z-10 group-[.sidebar-mini]:left-16 w-[calc(100%-200px)] group-[.sidebar-mini]:w-[calc(100%-64px)] left-[200px] ease-in duration-300 absolute items-center  justify-between p
```suggestion
<nav class="flex flex-wrap z-10 group-[.sidebar-mini]:left-16 w-[calc(100%-200px)] group-[.sidebar-mini]:w-[calc(100%-64px)] left-[200px] ease-in duration-300 absolute items-center justify-between py-3 px-6 bg-light-palette-p5">
```

2023-09-13 11:46 UTC, douglara commented on app/views/layouts/shared/_navbar_pipe.html.erb
> +      <div class="icon-color color-brand-palette-03">
Aqui seria bom converter essa class `icon-color` mas precisa ser visto se vai dar certo pois o bootstrap pode sobre escrevendo ou usando algum !important, caso não seja possível mapeamos para fazer a conversão quando for removido o bootstrap

2023-09-13 11:46 UTC, douglara commented on app/views/layouts/shared/_navbar_pipe.html.erb
> +<div class="flex items-center ">
```suggestion
<div class="flex items-center">
```

2023-09-13 11:46 UTC, douglara commented on app/views/layouts/shared/_navbar_pipe.html.erb
> +<!-- Dropdown menu -->
```suggestion
<%# Dropdown menu  %>
```

Aqui da para usarmos os comentários em ruby, assim esse dado não é trafegado =)

2023-09-13 14:14 UTC, YukioArie commented
@douglara fiz os commits de correção de todos os comentários acima.
Obs: Algumas classes do tailwind, margins e paddings, estão com valores diferentes quando aplicados em relação a documentação 

![image](https://github.com/douglara/woofed-crm/assets/45243355/afb3b7cf-2dfd-4eba-87b1-6519d15ff93c)

![image](https://github.com/douglara/woofed-crm/assets/45243355/8eea04b9-57bb-435c-8425-b966ad14e3dc)

Nesse caso eu setei mr-[1rem] na tag para ficar com o espaçamento certo, mas achei estranho os valores estarem diferentes em relação a documentação

2023-09-14 10:23 UTC, douglara commented
> @douglara fiz os commits de correção de todos os comentários acima. Obs: Algumas classes do tailwind, margins e paddings, estão com valores diferentes quando aplicados em relação a documentação
> 
> ![image](https://user-images.githubusercontent.com/45243355/267682657-afb3b7cf-2dfd-4eba-87b1-6519d15ff93c.png)
> 
> ![image](https://user-images.githubusercontent.com/45243355/267683084-8eea04b9-57bb-435c-8425-b966ad14e3dc.png)
> 
> Nesse caso eu setei mr-[1rem] na tag para ficar com o espaçamento certo, mas achei estranho os valores estarem diferentes em relação a documentação

Sim 😕 deve ser conflito com as classes do bootstrap mas devemos resolver quando concluir a migração.

2023-09-14 10:24 UTC, douglara commented on app/views/layouts/shared/_navbar_pipe.html.erb
> +<!-- Dropdown menu -->
Esse aqui ainda esta pendente

2023-09-14 10:48 UTC, douglara requested changes
Massaaa heim boa!

Reparei nesse ajuste somente agora, só ajustar a largura/altura do botão para ficar alinhado com o select.

![image](https://github.com/douglara/woofed-crm/assets/14988496/90e9b101-66f0-4979-bb39-542d483fe53d)

![image](https://github.com/douglara/woofed-crm/assets/14988496/23aeb0de-9a42-4f66-8851-4e91f31ded2b)

![image](https://github.com/douglara/woofed-crm/assets/14988496/fe4b44b4-0271-4b07-8af0-7d0e4662f543)

![image](https://github.com/douglara/woofed-crm/assets/14988496/7d18c4c4-1183-4c4e-be19-0240cb03aacb)

2023-09-14 10:48 UTC, douglara commented on app/views/layouts/application.html.erb
> +    <%= favicon_link_tag asset_path('favicon.svg') %>
O favicon acho que é melhor utilizar em format `.png` pois alguns navegadores não suportam `.svg`
![image](https://github.com/douglara/woofed-crm/assets/14988496/c2eb39f2-c60d-4437-9ef8-5c257aee57c5)
Talvez colocando na /public pode ser melhor pois acaba não passando por compilações do webpack.
É legal colocar em tamanhos diferentes para ficar bom nos celulares e também em dispositivos apple, segue um exemplo:
https://github.com/chatwoot/chatwoot/blob/616371adbbb3a1e6cb6ed93331c9cb8723f01634/app/views/layouts/vueapp.html.erb#L26C1-L26C1

https://en.wikipedia.org/wiki/Favicon

2023-09-14 23:25 UTC, YukioArie commented on app/views/layouts/application.html.erb
> +    <%= favicon_link_tag asset_path('favicon.svg') %>
Fiz o commit da favicon na branch de deal page layout. Esses primeiros pull requests estão bagunçados, mas amn irei organizar para poder fazer os commits no repositório principal, sem ser no meu fork 😀.

2023-09-14 23:35 UTC, YukioArie commented on app/views/layouts/application.html.erb
> +    <%= favicon_link_tag asset_path('favicon.svg') %>
Fiz o commit da correção no tamanho do botão da navbar na outra branch tmb

2023-09-15 14:49 UTC, closed without merging