Add create deal product frontend
douglara/woofed-crm pull request #332
Opened 2024-05-24 04:38 UTC by YukioArie

2024-06-03 21:57 UTC, douglara requested changes

2024-06-03 21:57 UTC, douglara commented on app/views/accounts/contacts/new.html.erb
> +  <div id="drawer-right-example" data-controller='drawer' class="fixed ease-in duration-300 top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-2/5 dark:b
```suggestion
  <div id="drawer-right" data-controller='drawer' class="fixed ease-in duration-300 top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-2/5 dark:bg-gray-800" tabindex="-1" aria-labelledby="drawer-right-label">
```

2024-06-03 21:57 UTC, douglara commented on app/views/accounts/contacts/new.html.erb
> +        <span class="sr-only">Close menu</span>
```suggestion
```

2024-06-03 21:57 UTC, douglara commented on app/views/accounts/products/new.html.erb
> +  <div id="drawer-right-example" data-controller='drawer' class="fixed ease-in duration-300 top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-2/5 dark:b
```suggestion
  <div id="drawer-right" data-controller='drawer' class="fixed ease-in duration-300 top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-2/5 dark:bg-gray-800" tabindex="-1" aria-labelledby="drawer-right-label">
```

2024-06-03 21:57 UTC, douglara commented on app/views/accounts/products/new.html.erb
> +        <span class="sr-only">Close menu</span>
```suggestion
```

2024-06-03 21:57 UTC, douglara commented on app/views/accounts/deal_products/_select_product_search_product.html.erb
> +        Quantidade: <%= model.quantity_available %>
Aqui falta a tradução

2024-06-03 21:57 UTC, douglara commented on app/views/components/_select_search.html.erb
> +  <%= hidden_field_tag hidden_field_name, nil, data: { 'select-search-target': 'modelId'} %>
Ficou bastante variáveis para passar mas não esta complicado de entender, bora seguir nesse approach

2024-06-04 02:32 UTC, YukioArie commented on app/views/components/_select_search.html.erb
> +  <%= hidden_field_tag hidden_field_name, nil, data: { 'select-search-target': 'modelId'} %>
Boa, vamos componetizar em um outro card

2024-06-04 02:33 UTC, YukioArie commented on app/views/accounts/deal_products/_select_product_search_product.html.erb
> +        Quantidade: <%= model.quantity_available %>
Acabei esquecendo desse detalher 😄

2024-06-04 04:35 UTC, merged