Add webpush notification
douglara/woofed-crm pull request #340
Opened 2024-06-07 04:55 UTC by YukioArie

2024-07-19 00:42 UTC, douglara requested changes
Aqui seria legal permitir o check box somente se as notificações estiverem habilitadas.
Vou criar um outro card para melhorarmos esse ponto

![image](https://github.com/user-attachments/assets/c9fe0418-44c1-4fad-8028-bafd0efc798d)

2024-07-19 00:42 UTC, douglara commented on app/use_cases/pwa/send_notifications_worker.rb
> +  self.queue_adapter = :good_job
```suggestion
  self.queue_adapter = :good_job

```

2024-07-19 00:46 UTC, douglara commented
Tem alguns conflitos nesse PR para corrigir

2024-07-23 01:26 UTC, douglara requested changes

2024-07-23 01:26 UTC, douglara commented on app/use_cases/pwa/send_notifications_worker.rb
> +        if subscription.user.webpush_notify_on_event_completion?
Hmmm então aqui não seria algo como "evento expirou"? event completion me parece que o evento foi completado com sucesso.

2024-07-30 04:27 UTC, YukioArie commented on app/use_cases/pwa/send_notifications_worker.rb
> +        if subscription.user.webpush_notify_on_event_completion?
Tem razão, vou mudar para `webpush_notify_on_event_expired?`.

2024-07-31 11:05 UTC, douglara requested changes

2024-07-31 11:05 UTC, douglara commented on spec/controllers/accounts/contacts/events_controller_spec.rb
> +        # end
Esse caso aqui porque foi comentado?

2024-07-31 12:37 UTC, YukioArie commented on spec/controllers/accounts/contacts/events_controller_spec.rb
> +        # end
Temos q resolvê-lo 🤔

2024-07-31 12:44 UTC, merged