Improve product attachments frontend
douglara/woofed-crm pull request #343
Opened 2024-06-14 05:47 UTC by YukioArie

2024-07-23 09:35 UTC, douglara requested changes

2024-07-23 09:35 UTC, douglara commented on app/views/accounts/products/_drag_and_drop.html.erb
> +      <p class="text-xs text-gray-500 dark:text-gray-400">MAX. 1gb</p>
Aqui seria 40 mb

2024-07-23 09:35 UTC, douglara commented on spec/controllers/accounts/products_controller_spec.rb
> +                                        description: 'Product description', attachments_attributes: [{ file: get_file('hello_world_41mb.png') }] } }
Acho bem legal ter esse teste aqui porem anexar um arquivo de 40 mb no código fonte não é muito bom 🙁
Algumas opções para contornarmos:
- Mockar a validação
- Configurar o tamanho máximo permitido de forma dinâmica

2024-07-23 09:46 UTC, douglara requested changes
![image](https://github.com/user-attachments/assets/8291662e-9d67-4a0f-90d0-2f3042f9c62a)

Ai no seu o carousel esta funcionando?

2024-07-30 04:45 UTC, YukioArie commented
Para mim o carousel está ok:

![image](https://github.com/user-attachments/assets/d03d534b-68f3-4d99-88d8-8d0f29cd2da0)

2024-07-30 04:45 UTC, YukioArie commented on app/views/accounts/products/_drag_and_drop.html.erb
> +      <p class="text-xs text-gray-500 dark:text-gray-400">MAX. 1gb</p>
Boa!

2024-07-30 04:55 UTC, YukioArie commented on spec/controllers/accounts/products_controller_spec.rb
> +                                        description: 'Product description', attachments_attributes: [{ file: get_file('hello_world_41mb.png') }] } }
Boa, consegui fazer o mock 😄

2024-07-30 12:26 UTC, merged