Fix and refactor contact builder
douglara/woofed-crm pull request #353
Opened 2024-06-29 10:15 UTC by YukioArie

2024-07-09 03:28 UTC, douglara requested changes

2024-07-09 03:28 UTC, douglara commented on spec/builders/contact_builder_spec.rb
> +      end
Aqui acho que vale verificar se o id do objeto retornado bate com o do contact

2024-07-09 03:28 UTC, douglara commented on spec/builders/contact_builder_spec.rb
> +      end
Aqui como ele vai inicializar um objeto novo que não esta persistido no banco da para verificar se o id esta em branco.

2024-07-09 03:28 UTC, douglara commented on spec/builders/contact_builder_spec.rb
> +        expect(contact_found.email).to eq(contact.email)
Aqui confirmar que o id esta em branco

2024-07-09 03:28 UTC, douglara commented on spec/builders/contact_builder_spec.rb
> +        expect(contact_found.email).to eq('')
Aqui também da para confirmar se o id esta em branco

2024-07-10 11:00 UTC, YukioArie commented on spec/builders/contact_builder_spec.rb
> +      end
Show!

2024-07-10 11:11 UTC, merged