Add pagination to stages
douglara/woofed-crm pull request #402
Opened 2024-09-03 05:33 UTC by YukioArie

2024-09-05 02:32 UTC, douglara requested changes

2024-09-05 02:32 UTC, douglara commented on app/controllers/accounts/stages_controller.rb
> +    @stage = current_user.account.stages.find(params[:id])
```suggestion
    @stage = Stages.find(params[:id])
```

2024-09-05 02:32 UTC, douglara commented on app/models/deal.rb
> +    broadcast_replace_later_to self, partial: 'accounts/pipelines/deal', locals: { pipeline: }
Esse pipeline: não esta errado?

2024-09-05 02:32 UTC, douglara commented on app/models/deal.rb
> +    stage.broadcast_updates(status) if (previous_changes.keys - ['updated_at']) == ['position']
```suggestion
    stage.broadcast_updates(status) if (previous_changes.key?('stage_id'))
```

2024-09-05 02:32 UTC, douglara commented on app/models/deal.rb
> +    if (previous_changes.keys - ['updated_at']) == ['status']
```suggestion
    if (previous_changesprevious_changes.key?('stage_id'))
```

2024-09-05 02:32 UTC, douglara commented on app/models/stage.rb
> +  def broadcast_updates(filter_status_deal)
Puts esses streams esta complicado heim..
Bora criar um card a parte para resolvermos melhor esse problema?

2024-09-10 04:33 UTC, douglara requested changes
https://github.com/user-attachments/assets/b2fa57da-f993-4fcd-bdd2-1d29f4885ec8

Puts isso aqui do scroll resetar é bem ruim 🫤

2024-09-11 11:24 UTC, douglara requested changes

2024-09-11 11:24 UTC, douglara commented on app/models/deal.rb
> +    if (previous_changes.keys - ['updated_at']) == ['status']
```suggestion
    if previous_changes.except('updated_at').keys == ['position']
```

2024-09-12 00:30 UTC, YukioArie commented on app/models/stage.rb
> +  def broadcast_updates(filter_status_deal)
Bora!

2024-10-04 20:55 UTC, merged