Add login frontend
douglara/woofed-crm pull request #414
Opened 2024-09-17 04:44 UTC by YukioArie

2024-09-23 21:57 UTC, douglara requested changes

2024-09-23 21:57 UTC, douglara commented on app/controllers/application_controller.rb
> +  end
Testar esse método

2024-09-23 21:57 UTC, douglara commented on app/controllers/installation_controller.rb
> +  end
Testar esse método

2024-09-23 21:57 UTC, douglara commented on app/views/devise/registrations/new.html.erb
> +        <% if Installation.installation_flow? %>
Isso aqui da para remover

2024-09-23 21:57 UTC, douglara commented on app/views/devise/registrations/new.html.erb
> +    Você ainda não possui cadastro na Woofed mas não se preocupe você dar continuedade seu cadastro.
i18n

2024-09-23 21:57 UTC, douglara commented on app/views/devise/sessions/new.html.erb
>  <% if Installation.installation_flow? %>
Aqui também da para remover

2024-09-24 00:43 UTC, YukioArie commented on app/views/devise/registrations/new.html.erb
> +        <% if Installation.installation_flow? %>
Show, removido.

2024-09-24 00:43 UTC, YukioArie commented on app/views/devise/registrations/new.html.erb
> +    Você ainda não possui cadastro na Woofed mas não se preocupe você dar continuedade seu cadastro.
Show, adicionado.

2024-09-24 11:43 UTC, douglara requested changes
- [ ] Correção dos testes
- [x] Resolver routes/before_action após instalado
- [x] Foto
- [x] Relacionar instalação ao usuário que instalou
- [x] Testar o fluxo de enviar as informações da instalação
- [x] status na woofed store
- [x] Can't verify CSRF token authenticity.
- [ ] Pegar todos os arquivos de fotos e videos, armazenar no bucket e remover do codigo.

2024-10-03 23:54 UTC, douglara requested changes

2024-10-03 23:54 UTC, douglara commented on app/controllers/application_controller.rb
> +    redirect_to installation_new_path and return
Aqui algo como:
```suggestion
    if Installation.installation_flow? && !request.path.include?('/installation')
      redirect_to installation_new_path and return
    end
```

Não fica mais simples de entender?

2024-10-04 11:27 UTC, douglara requested changes

2024-10-04 11:27 UTC, douglara commented on app/controllers/application_controller.rb
> +# end
```suggestion
```

2024-10-04 11:27 UTC, douglara commented on app/controllers/installation_controller.rb
> +
```suggestion
```

2024-10-04 11:27 UTC, douglara commented on app/controllers/installation_controller.rb
> +      bypass_sign_in(@user)
Hmmm onde esse método esta sendo definido?

2024-10-04 11:27 UTC, douglara commented on app/controllers/installation_controller.rb
> +
```suggestion
  private
```

2024-10-04 11:27 UTC, douglara commented on app/models/installation/complete.rb
> +    return false unless Current.account.present?
```suggestion
    return false if Current.account.blank?
```

2024-10-04 11:27 UTC, douglara commented on app/models/installation/complete.rb
> +    user = self.user
Ue acho que não precisa desse user hehe

2024-10-04 11:27 UTC, douglara commented on app/views/devise/sessions/new.html.erb
> +<% end %>
Esse if da para remover

2024-10-04 11:27 UTC, douglara commented on app/views/layouts/installations_loading.html.erb
> +              <%= link_to 'Termos de Serviço', 'https://woofedcrm.com/terms-of-service/', target: :_blank %>
Aqui faltou o i18n

2024-10-04 11:27 UTC, douglara commented on app/views/layouts/installations_loading.html.erb
> +              <%= link_to 'Política de Privacidade', 'https://woofedcrm.com/policy-terms/', target: :_blank %>
Aqui faltou o i18n

2024-10-04 11:27 UTC, douglara commented on app/views/layouts/devise.html.erb
> +              <%= link_to 'Termos de Serviço', 'https://woofedcrm.com/terms-of-service/', target: :_blank %>
Aqui faltou o i18n

2024-10-04 11:27 UTC, douglara commented on app/views/layouts/devise.html.erb
> +              <%= link_to 'Política de Privacidade', 'https://woofedcrm.com/policy-terms/', target: :_blank %>
Aqui faltou o i18n

2024-10-04 21:45 UTC, YukioArie commented on app/views/layouts/installations_loading.html.erb
> +              <%= link_to 'Política de Privacidade', 'https://woofedcrm.com/policy-terms/', target: :_blank %>
Como ainda n temos termos de privacidade e serviço, eu irei remover esses links. Quando a gnt tiver essas paginas estruturadas, a gnt coloca elas e faz o i18n. Eu tinha criado para o google aceitar a autenticação, como eles já aceitaram, n tem necessidade de ter eles. Tem um outro ponto tbm, q esse layout n está sendo utilizado, acho q irei remover esse arquivo tbm.

2024-10-04 21:45 UTC, YukioArie commented on app/views/layouts/installations_loading.html.erb
> +              <%= link_to 'Termos de Serviço', 'https://woofedcrm.com/terms-of-service/', target: :_blank %>
Como ainda n temos termos de privacidade e serviço, eu irei remover esses links. Quando a gnt tiver essas paginas estruturadas, a gnt coloca elas e faz o i18n. Eu tinha criado para o google aceitar a autenticação, como eles já aceitaram, n tem necessidade de ter eles. Tem um outro ponto tbm, q esse layout n está sendo utilizado, acho q irei remover esse arquivo tbm.

2024-10-04 21:45 UTC, YukioArie commented on app/views/layouts/devise.html.erb
> +              <%= link_to 'Termos de Serviço', 'https://woofedcrm.com/terms-of-service/', target: :_blank %>
Como ainda n temos termos de privacidade e serviço, eu irei remover esses links. Quando a gnt tiver essas paginas estruturadas, a gnt coloca elas e faz o i18n. Eu tinha criado para o google aceitar a autenticação, como eles já aceitaram, n tem necessidade de ter eles.

2024-10-04 21:45 UTC, YukioArie commented on app/views/layouts/devise.html.erb
> +              <%= link_to 'Política de Privacidade', 'https://woofedcrm.com/policy-terms/', target: :_blank %>
Como ainda n temos termos de privacidade e serviço, eu irei remover esses links. Quando a gnt tiver essas paginas estruturadas, a gnt coloca elas e faz o i18n. Eu tinha criado para o google aceitar a autenticação, como eles já aceitaram, n tem necessidade de ter eles.

2024-10-04 21:46 UTC, YukioArie commented on app/views/devise/sessions/new.html.erb
> +<% end %>
Show!

2024-10-04 21:47 UTC, YukioArie commented on app/controllers/application_controller.rb
> +    redirect_to installation_new_path and return
Tem razão, vou testar para ver se n quebra os testes

2024-10-04 21:48 UTC, YukioArie commented on app/controllers/installation_controller.rb
> +      bypass_sign_in(@user)
Esse método é do devise, esse update_step_2 é o step q a pessoa atualiza a senha. Por padrão, quando a gnt atualiza a senha, o devise desloga da sessão, fazendo o usuário retornar para a tela de login. Esse metodo é para o usuário fazer o sign in logo apos a atualização da senha para n ter esse comportamento de deslogar.

2024-10-04 21:48 UTC, YukioArie commented on app/models/installation/complete.rb
> +    return false unless Current.account.present?
Ficou melhor, rs

2024-10-04 21:53 UTC, YukioArie commented on app/models/installation/complete.rb
> +    user = self.user
É q estou chamando ele nos parametros user_details ali em baixo, poderia chamar ali direto o `self.user`, mas n sei qual opção é o melhor, rs

2024-10-08 16:00 UTC, douglara requested changes

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +          expect(user.reload.valid_password?('Password1!')).to be_falsey
Pelo que entendi o objetivo dessa linha é validar se o usuário foi atualizado né? Talvez mudar para verificar o full_name que deve ser `Yukio teste``deixa o teste mais claro

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +            load "#{Rails.root}/app/controllers/application_controller.rb"
Agora que adicionamos nos before(:each) ainda precisa dessas linhas?

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +    context 'when it is an unauthenticated user' do
Hmmm tem necessidade de testar autenticado e não?

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +RSpec.describe InstallationController, type: :request do
Esse arquivo realmente esta com testes de mais, bora dar uma enxugada nisso

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +                                                 .and change(User, :count).by(0)
Esses testes validam os parâmetros, da para unificar eles

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +        end
Aqui talvez vale a pena criar um testes quando o email que chega nos `params` é o mesmo do `let!(:user) { create(:user, account:) }`. Nessa situação o comportamento é de atualizar o user

2024-10-08 16:00 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +      context 'when it is an unauthenticated user' do
Esses espaçamentos ajuda a identificar que são contextos que não possuem relação

```suggestion
      end

      context 'when it is an unauthenticated user' do
```

2024-10-09 01:25 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Aqui é necessário mesmo?

2024-10-09 01:25 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +            first_installation.app_reload
Aqui é necessário mesmo?

2024-10-09 02:02 UTC, douglara requested changes

2024-10-09 02:02 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +    context 'when it is an unauthenticated user' do
Pelo que eu vi os testes são iguais e tem esse except
![image](https://github.com/user-attachments/assets/942f806c-2661-4ef8-bd34-daecd2306d4b)

2024-10-09 02:02 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Precisa dessas linhas?

2024-10-09 02:02 UTC, douglara commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Precisa dessas linhas?

2024-10-09 12:02 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Acho q n msm, já esta sendo chamado no before(:each)

2024-10-09 12:02 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Acho q n msm, já esta sendo chamado no before(:each)

2024-10-09 12:03 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            Rails.application.reload_routes!
Acho q n msm, já esta sendo chamado no before(:each)

2024-10-09 12:04 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +RSpec.describe InstallationController, type: :request do
Acho q resolvermos, rs 😃

2024-10-09 12:04 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +                                                 .and change(User, :count).by(0)
Resolvido!

2024-10-09 12:06 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +          expect(user.reload.valid_password?('Password1!')).to be_falsey
Resolvido!

2024-10-09 12:06 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            load "#{Rails.root}/app/controllers/application_controller.rb"
Resolvido!

2024-10-09 12:11 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +        end
Tem razão!
Adicionei esses campos:
```ruby
    expect(last_user.full_name).to eq(params[:user][:full_name])
    expect(last_user.email).to eq(params[:user][:email])
```

2024-10-09 12:16 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            first_installation.app_reload
Nesse caso sim.
Se eu não coloco ele, o teste me retornará esse erro: 
```ruby
Failure/Error:
       expect do
         get '/installation/create',
             params: { user: { email: 'yukio@email.com', full_name: 'Yukio teste' },
                       installation: { id: 1, key1: 'key1teste', key2: 'key2teste', token: 'tokenteste' } }
       end.to raise_error(ActionController::RoutingError)
     
       expected ActionController::RoutingError but nothing was raised
     # ./spec/controllers/installation_controller_spec.rb:147:in `block (6 levels) in <top (required)>'
```

2024-10-09 12:18 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +            first_installation.app_reload
No caso como o installation esta com status `completed`, essa rota n deveria existir, mas na verdade ele ainda existe. No caso eu rodei esse comando `first_installation.app_reload` para ele retirar essa rota. N sei pq no before(:each) essa rota já n está sendo removido.

2024-10-09 12:19 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +      context 'when it is an unauthenticated user' do
Boa! Adicionei essa alteração.

2024-10-09 12:22 UTC, YukioArie commented on spec/controllers/installation_controller_spec.rb
> +    context 'when it is an unauthenticated user' do
Resolvido!
Removi o context `when there is an installation` do context `when it is an authenticated user`.

2024-10-09 12:44 UTC, YukioArie commented on app/controllers/application_controller.rb
> +    redirect_to installation_new_path and return
O autosave está mudando para esse formato:
```ruby
    return unless Installation.installation_flow? && !request.path.include?('/installation')

    redirect_to installation_new_path and return
``` 
Acho q dessa forma da para entender tbm, acho q o autosave n curte muito ifs 😄

2024-10-09 12:47 UTC, YukioArie commented on app/controllers/application_controller.rb
> +# end
Boa! Acabei esquecendo de remover.

2024-10-09 12:47 UTC, YukioArie commented on app/controllers/installation_controller.rb
> +
Boa!

2024-10-09 12:48 UTC, YukioArie commented on app/controllers/installation_controller.rb
> +
Boa!

2024-10-11 01:17 UTC, merged