Add deal users
douglara/woofed-crm pull request #435
Opened 2024-12-12 06:37 UTC by YukioArie

2024-12-13 12:46 UTC, douglara requested changes

2024-12-13 12:46 UTC, douglara commented on app/controllers/accounts/deal_assignees_controller.rb
> +    @deal_assignee = DealAssignee.new(deal_assignees_params)
Aqui tem algum teste?

2024-12-13 12:46 UTC, douglara commented on app/controllers/accounts/deal_assignees_controller.rb
> +    @users = if params[:query].present?
Aqui talvez podemos buscar por email e telefone também

2024-12-13 12:46 UTC, douglara commented on app/models/deal_assignee.rb
> +  validates :user_id, uniqueness: { scope: :deal_id, message: :taken }
Hmm o qque é esse taken?

2024-12-13 12:46 UTC, douglara commented on app/views/accounts/deals/details/deal_assignees/_show.html.erb
> +  <%= turbo_frame_tag DealAssignee.new do %>
Aqui não pode seria ser? 

```suggestion
  <%= turbo_frame_tag deal do %>
```

2024-12-14 03:46 UTC, YukioArie commented on app/controllers/accounts/deal_assignees_controller.rb
> +    @users = if params[:query].present?
Boa ideia! Adicionei essa funcionalidade.

2024-12-14 03:59 UTC, YukioArie commented on app/models/deal_assignee.rb
> +  validates :user_id, uniqueness: { scope: :deal_id, message: :taken }
Esse taken é a mensagem de erro. Ele está localizado no `config/locales/models/deal_assignee/en.yml:19`.
```ruby
en:
  activerecord:
    models:
      deal_assignee:
        one: "Assignee"
        other: "Assignees"
        new: "New assignee"
        edit: "Edit assignee"
        add: "Add assignee"
    attributes:
      deal_assignee:
        user: "User"
        deal: "Deal"
    errors:
      models:
        deal_assignee:
          attributes:
            user_id:
              taken: "is already associated with this deal"
``` 
Eu coloquei esse nome `taken`, pq a mensagem padrão que o rails retorna quando acontece um erro de uniqueness é `has already been taken`. Logo, para seguir uma convenção, eu optei por nomeá-lo dessa forma.
Segue um exemplo do i18n do próprio rails que nomeia esse erro dessa forma: https://github.com/rails/rails/blob/1f9b696eb5d2f907cdb637e19989964bb9c3bd59/activerecord/lib/active_record/locale/en.yml#L11

```ruby
  # Default error messages
  errors:
    messages:
      required: "must exist"
      taken: "has already been taken"
```

2024-12-14 03:59 UTC, YukioArie commented on app/controllers/accounts/deal_assignees_controller.rb
> +    @deal_assignee = DealAssignee.new(deal_assignees_params)
Yep

2024-12-14 04:03 UTC, douglara approved these changes
Boaaa gostei dos testes

2024-12-14 04:03 UTC, douglara commented on spec/models/deal_assignee_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Esse arquivo da para excluir

2024-12-14 04:20 UTC, YukioArie commented on app/views/accounts/deals/details/deal_assignees/_show.html.erb
> +  <%= turbo_frame_tag DealAssignee.new do %>
Nesse caso eu acho q n é recomendado. Seguindo o fluxo do hotwire, ao clicar no botão do `new` do `DealAssignee`, ele vai redirecionar na pagina de new do `DealAssignee` e na resposta dessa action, ele vai ter q ter o turbo_frame id com DealAssignee.new, pois ele está no fluxo de criação do `DealAssignee`. Dessa forma, ele acaba seguindo o fluxo padrão do hotwire. Geralmente, quando colocamos o turbo_frame com o id do model, como é a situação que vc comentou, Ele segue o fluxo de edit e n de criar. E mesmo que fosse no de criar, n faz sentido colocar com o id do model deal, sendo que eu estou criando o `DealAssignee`. Fora que já existe um turbo_frame com esse mesmo id que vc aconselhou na pagina, a chance de dar conflito é grande.

## Segue o fluxo de criação
![image](https://github.com/user-attachments/assets/8e41b8d6-1188-4729-8055-7d52195d76b7)

![image](https://github.com/user-attachments/assets/14a0d4c4-fda7-4574-a00b-7fee191f43ea)

![image](https://github.com/user-attachments/assets/e91d7795-fe38-42bc-b5e3-e05edd2ab27b)

![image](https://github.com/user-attachments/assets/2fadc49a-bc0d-41f3-a9c0-ba17fa7cf96f)



## Segue o fluxo de editar

![image](https://github.com/user-attachments/assets/910dd844-e828-4e6f-b502-15a2738133bd)

![image](https://github.com/user-attachments/assets/de1451c9-4fc1-4a17-a998-05a4a431d4bb)

![image](https://github.com/user-attachments/assets/9c2a28c4-e224-4b3d-898d-95b19053d591)

### Fonte: https://www.hotrails.dev/turbo-rails/turbo-frames-and-turbo-streams

Lembrando que quando eu coloco o assim:
```ruby
<%= turbo_frame_tag DealAssignee.new do %>
``` 
ele retorna dessa forma: 
```ruby
 <turbo-frame id="new_deal_assignee" >
``` 

E quando colocamos dessa forma: 
```ruby
<%= turbo_frame_tag deal do %>
``` 
Ele retorna dessa forma: 
```ruby
<turbo-frame id="deal_4">
```

2024-12-14 04:20 UTC, YukioArie commented on spec/models/deal_assignee_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Vai dormir, rs

2024-12-14 05:00 UTC, douglara commented on app/views/accounts/deals/details/deal_assignees/_show.html.erb
> +  <%= turbo_frame_tag DealAssignee.new do %>
Entendi nesse guia tem alguns exemplos chamando na própria view.
Tinha a ideia que no controller inicializava/criava os objetos que a view iria consumir mas boaa bora seguir

2024-12-14 05:04 UTC, douglara commented on app/models/deal_assignee.rb
> +  validates :user_id, uniqueness: { scope: :deal_id, message: :taken }
Boaa blz!

2024-12-14 05:05 UTC, merged