Add created_by_id to deal
douglara/woofed-crm pull request #436
Opened 2024-12-18 21:44 UTC by YukioArie

2024-12-19 11:51 UTC, douglara requested changes

2024-12-19 11:51 UTC, douglara commented on app/controllers/accounts/deals_controller.rb
>      # @deal = DealBuilder.new(current_user, deal_params).perform
Hmmm será que não da para utilizar o DealBuilder?

2024-12-19 11:51 UTC, douglara commented on app/controllers/api/v1/accounts/deals_controller.rb
> +    @deal.creator = @current_user
Hmmm será que não da para utilizar o DealBuilder?

2024-12-19 11:51 UTC, douglara commented on app/models/deal.rb
> +  belongs_to :creator, class_name: 'User', foreign_key: 'created_by_id', optional: true
Esse campo seria bom não ser optional mas como já esta rodando vamos ter que fazer em duas etapas

2024-12-19 12:01 UTC, YukioArie commented on app/models/deal.rb
> +  belongs_to :creator, class_name: 'User', foreign_key: 'created_by_id', optional: true
Esse campo eu deixei opcional para a pessoa poder excluir o `user`. Sem esse campo acredito q ele vai dar erro ao excluir o usuário.

2024-12-19 12:02 UTC, YukioArie commented on app/controllers/accounts/deals_controller.rb
>      # @deal = DealBuilder.new(current_user, deal_params).perform
Posso testar aqui, esse `DealBuilder` só está sendo usado na importação de negocios.

2024-12-19 13:05 UTC, YukioArie commented on app/controllers/accounts/deals_controller.rb
>      # @deal = DealBuilder.new(current_user, deal_params).perform
Consegui fazer pelo `DealBuilder`. Tive q fazer ajuste no `DealBuilder`, pois ele estava funcionando somente para a importação de negocios via planilha. No processo de importação de negocios via planilha, ele recebe o deal_params com o `contact_attributes` preenchido, e o contact_id em branco. Logo, toda vez q ele chamava o DealBuilder, ele criava o contato, ou se vc colocasse o parametro `contact_search_if_exists` como true, ele pesquisava se o contato existisse atraves dos `contact_attributes`. Como no processo de criação dos negocios o `contact_attributes` n é preenchido e sim o `contact_id`, eu tive q fazer esse ajuste:
```ruby
  def build
    @deal = Deal.new(deal_params(@params).merge(created_by_id: @user.id))
    build_contact 
    @deal
  end
``` 

```ruby
  def build
    @deal = Deal.new(deal_params(@params).merge(created_by_id: @user.id))
    build_contact if @deal.contact.blank?
    @deal
  end
``` 
app/builders/deal_builder.rb:10

Obs: N queria ter mexido nesse DealBuilder, pois ele n tem teste unitario, e alterando ele afeta diretamente a importação de negocios q tbm n tem testes por ser uma POC. Mas acredito q isso n seja um problema.

2024-12-19 13:06 UTC, YukioArie commented on app/controllers/api/v1/accounts/deals_controller.rb
> +    @deal.creator = @current_user
Feito!

2024-12-21 05:36 UTC, douglara approved these changes
Boaa!

2024-12-21 06:38 UTC, merged