Deal page layout structure
douglara/woofed-crm pull request #46
Opened 2023-09-15 14:50 UTC by YukioArie

2023-09-18 22:49 UTC, douglara requested changes
Massaa heim ganhando forma 😍

Essa parte da página é um pouco maior

![image](https://github.com/douglara/woofed-crm/assets/14988496/f8ee0cce-77a7-4525-8b39-9bc5ce83deaf)


![image](https://github.com/douglara/woofed-crm/assets/14988496/3461d610-9458-4f1e-8423-ba1ae2b18a6c)


Por alguma razão esses hovers pararam de funcionar
![image](https://github.com/douglara/woofed-crm/assets/14988496/de2da92e-3e97-443e-88d6-c79b18d03530)

2023-09-18 22:49 UTC, douglara commented on app/views/accounts/deals/_details.html.erb
> +<div class="p-1 bg-light-palette-p5 rounded-md border-light-palette-p3 h-full">
Aqui na verdade não é full
![image](https://github.com/douglara/woofed-crm/assets/14988496/95cb9899-6076-450e-bf24-1255fdf7c3ea)

2023-09-18 22:49 UTC, douglara commented on app/views/layouts/internal.html.erb
> +      </div>
```suggestion
        <div class="">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
```
Aqui acho que vale um tab heheh

2023-09-18 22:49 UTC, douglara commented on app/views/layouts/internal.html.erb
>        </div>
```suggestion
        <div class="main-content">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
```

2023-09-18 22:49 UTC, douglara commented on app/views/layouts/shared/_navbar_deal.html.erb
> +    <i data-lucide="chevron-left"></i>
```suggestion
      <i data-lucide="chevron-left"></i>
```

2023-09-20 05:12 UTC, YukioArie commented
@douglara, o breadcrump no desktop está pronto! Agora só falta a versão mobile/tablet 🚀 
![Captura de Tela (16)](https://github.com/douglara/woofed-crm/assets/45243355/c3b751a4-a039-439a-8df7-3f409e2b5f85)

![Captura de Tela (17)](https://github.com/douglara/woofed-crm/assets/45243355/645004be-7109-4bd4-834f-7a20fc026d75)

2023-09-21 05:19 UTC, YukioArie commented
![image](https://github.com/douglara/woofed-crm/assets/45243355/e8e91ebc-3afb-4f83-a3fd-a869c8ccec66)

2023-09-25 21:37 UTC, douglara commented
## Review de ajustes visuais

Essa media query esta bem alta, talvez testar com `sm` ou `md` para ver como fica
![image](https://github.com/douglara/woofed-crm/assets/14988496/51a90fe0-37da-4f5d-b88a-4e88e25669e0)

Adicionar uma borda/margin no fim da página

![image](https://github.com/douglara/woofed-crm/assets/14988496/2cd6b801-bb25-4e38-87f2-5f1190594228)


Ajustar texto
![image](https://github.com/douglara/woofed-crm/assets/14988496/a7299ea9-2903-4335-8a46-141cfb391a12)


Cor icone
![image](https://github.com/douglara/woofed-crm/assets/14988496/c9e70e6d-d2d4-4d7f-8d67-a3fd8d11a567)


Criação do backdrop duplicado
![image](https://github.com/douglara/woofed-crm/assets/14988496/25bc1ee4-d2bb-4f75-bdd1-09863a91b28b)



Ajustar para não escurecer o fundo e a altura do modal
![image](https://github.com/douglara/woofed-crm/assets/14988496/abbffcfe-3b51-4cce-802f-b8ce46b885bf)

![image](https://github.com/douglara/woofed-crm/assets/14988496/22dc925e-40f7-41c5-8c05-bee994bd5f7d)


Ajuste de fonte

![image](https://github.com/douglara/woofed-crm/assets/14988496/37d203c5-3390-44c1-8b8f-f20161e8ba64)

![image](https://github.com/douglara/woofed-crm/assets/14988496/eacdd022-0924-411c-b4d8-5c56a48218cd)



Borda não arredondada
![image](https://github.com/douglara/woofed-crm/assets/14988496/56db4d30-90b9-4b51-9723-3615108d18d6)

![image](https://github.com/douglara/woofed-crm/assets/14988496/a2a378a2-a22f-468e-80aa-9064b261a02b)


Ajuste da altura
![image](https://github.com/douglara/woofed-crm/assets/14988496/08287648-e1ad-4333-9a01-e07911c98e31)
![image](https://github.com/douglara/woofed-crm/assets/14988496/96e44755-7a69-4548-9169-ecf28d0451af)


Ajuste de altura do elemento
![image](https://github.com/douglara/woofed-crm/assets/14988496/bf0193e9-9201-4c41-afb7-78408a67e79b)
![image](https://github.com/douglara/woofed-crm/assets/14988496/33230d73-82c6-4835-a8e2-8016d154a93d)


Ajuste de borda

![image](https://github.com/douglara/woofed-crm/assets/14988496/1c130367-a658-454b-86fa-b88abb67ca13)
![image](https://github.com/douglara/woofed-crm/assets/14988496/e0755ac7-7d40-407e-916e-7aa302012b91)

2023-09-25 21:49 UTC, douglara commented
Ajustar esse botão

![image](https://github.com/douglara/woofed-crm/assets/14988496/ef1d3713-584f-4ea8-af2b-e8116b7363a9)

![image](https://github.com/douglara/woofed-crm/assets/14988496/b8712b82-0b82-4a56-a685-05758e247d95)


Hidden nesse botão
![image](https://github.com/douglara/woofed-crm/assets/14988496/f65f2595-0799-457d-9edc-6b714e8004fa)

2023-09-26 15:51 UTC, YukioArie commented
@douglara Fiz todos os reajustes visuais, exceto do modal e das fonts. Esses dois ultimos é legal deixar um card separado e depois consertaremos mas, por ora, o ideal é priorizar outros cards

2023-10-02 12:30 UTC, douglara commented
@YukioArie aqui da para fazer o merge com a development para resolver o conflito.

2023-10-02 12:34 UTC, douglara requested changes

2023-10-02 12:34 UTC, douglara commented on app/views/components/events/_form.html.erb
> +    <p class="mb-4 flex-[1_1_180px] min-[876px]:mb-0  text-gray-palette-p-1 font-semibold text-lg">Ações</p>
Ajustar o `min-[876px]:mb-0 ` que agora não é mais necessário

2023-10-02 12:34 UTC, douglara commented on app/views/layouts/internal.html.erb
> -
Esse arquivo aqui acho que não precisa ser alterado.

2023-10-02 12:34 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +        <div id="dropdownMenuActions" class="z-10 hidden !w-48 !-left-16  bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
Aqui remover os !important

2023-10-02 13:12 UTC, YukioArie commented on app/views/components/events/_form.html.erb
> +    <p class="mb-4 flex-[1_1_180px] min-[876px]:mb-0  text-gray-palette-p-1 font-semibold text-lg">Ações</p>
commit 3837830

2023-10-02 13:12 UTC, YukioArie commented on app/views/accounts/contacts/events/_event.html.erb
> +        <div id="dropdownMenuActions" class="z-10 hidden !w-48 !-left-16  bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
commit [705f6f4]

2023-10-02 13:28 UTC, YukioArie commented
@douglara Resolvi os conflitos e ajustei os espaçamentos

2023-10-02 13:31 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +          <main class="h-full overflow-auto md:p-8 bg-brand-palette-08">
@douglara Tive que adicionar essa responsive query no padding na main, pq na pagina do deal n terá espaçamento entre a navbar e o conteudo, diferente das demais paginas.

2023-10-03 10:21 UTC, douglara commented on app/assets/stylesheets/stages_nav.scss
> +ol a:nth-of-type(1){
Aqui talvez seja melhor adicionarmos um 
```suggestion
.stage-bar ol a:nth-of-type(1){
```

Pois dessa maneira atual acredito que vai ser aplicado esse comportamento em qualquer `ol` que aparece no site

2023-10-03 10:43 UTC, douglara commented on app/views/layouts/internal.html.erb
> +          <main class="h-full overflow-auto md:p-8 bg-brand-palette-08">
Entendi!
O ruim dessa opção é que em todo o sistema na versão `sm` ficara com padding 0

![image](https://github.com/douglara/woofed-crm/assets/14988496/58912878-45e1-4c20-9b04-6260e8d84463)

Algumas alternativas que pensei aqui:
- Aplicar um padding negativo nessa página com media query `sm`
- Criar um novo arquivo de layout para essa página
- Mover esse padding para dentro do `content_for` assim todo conteúdo deve aplicar seu próprio padding

2023-10-03 14:04 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +          <main class="h-full overflow-auto md:p-8 bg-brand-palette-08">
Estou fazendo exatamente a ultima opção por achar mais simples. Em cada conteudo estou setando o padding dele por ex: p-2 md:p-0 e a main cotinua com md:p-8 q é o espaçamento padrão para todos os conteudos na versão desktop

2023-10-04 01:47 UTC, douglara commented on app/assets/stylesheets/stages_nav.scss
> +ol a:last-child{
Nesse aqui também é bom adicionar o `stage-bar` e agora para ser aplicado precisamos adicionar lá na div pai desses `ol`

2023-10-04 02:18 UTC, douglara requested changes

2023-10-04 02:18 UTC, douglara commented on app/views/accounts/deals/_stages_nav_desktop.html.erb
> +<% end %>
Esse carinha seria legal estudarmos se tem alguma forma de unificar em uma renderização mas para agilizar vou criar uma issue e vemos mais pra frente.
#108

2023-10-04 02:18 UTC, douglara commented on app/views/layouts/shared/_navbar_deal.html.erb
> +  <%= link_to(:back, class: "flex border-solid border-2 border-light-palette-p3 rounded-md hover:bg-brand-palette-08 focus:bg-brand-palette-08 p-1.5") do %>
Esse link_to como `back` acho que não ta funcionando legal hehe talvez trocar seja uma boa

2023-10-04 02:18 UTC, douglara commented on app/views/layouts/internal.html.erb
> +          <main class="h-full overflow-auto md:p-8 bg-brand-palette-08">
Essa opção 3 acho que seria mais de colocar no arquivo:
 `app/views/accounts/deals/show.html.erb`
 
É o que carrega dentro do `content`

![image](https://github.com/douglara/woofed-crm/assets/14988496/94f58fe7-250f-45ce-866e-acd211a25d6e)

2023-10-04 02:18 UTC, douglara commented on app/views/accounts/contacts/events/_event.html.erb
> +        </div>
Esse trecho está meio fora do escopo desse card xD mas mandou bem nos ajustes

2023-10-04 02:18 UTC, douglara commented on app/views/accounts/deals/_details.html.erb
> +  </div>
Esse carinha seria legal estudarmos se tem alguma forma de unificar em uma renderização mas para agilizar vou criar uma issue e vemos mais pra frente.

2023-10-04 02:18 UTC, douglara commented on app/views/components/deals/_stages_nav.html.erb
> +<% deal.stage.pipeline.stages.each_with_index do | stage, index | %>
Vou aproveitar para já ajustar a renderização

2023-10-04 03:28 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +          <main class="h-full overflow-auto md:p-8 bg-brand-palette-08">
Pode ser, daí a gnt tira do main o p-8 e seta  em cada seção um padding

2023-10-04 11:26 UTC, douglara approved these changes

2023-10-04 11:26 UTC, merged