Change page layout
douglara/woofed-crm pull request #58
Opened 2023-09-22 21:16 UTC by douglara

2023-09-25 13:42 UTC, YukioArie commented
@douglara, acho q o meu código do layout ficou mais clean
![image](https://github.com/douglara/woofed-crm/assets/45243355/a33da621-7291-4226-a1bd-21e4dc0de199)

![image](https://github.com/douglara/woofed-crm/assets/45243355/acc85449-bd8c-4e8b-8a06-7fc350c2db0e)

![image](https://github.com/douglara/woofed-crm/assets/45243355/e9fca91e-4932-4a5a-b0d7-7633f263a74f)

2023-09-26 13:05 UTC, YukioArie requested changes
Acho interessante implementar o seu layout por ele respeitar o conteúdo interno sem precisar usar uma outra classe. Testei a sidebar e funcionou bem. 🚀

2023-09-26 13:05 UTC, YukioArie commented on app/views/layouts/internal.html.erb
>    <body class="group">
Acredito que podemos remover essa classe group do body

2023-09-26 13:05 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +        <aside class="w-60">
Talvez seja interessante usar a tag aside no arquivo da sidebar.

2023-09-26 13:05 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +          <nav class="h-20">
A tag nav tbm acredito que seja interessante colocar no arquivo da navbar

2023-09-26 21:20 UTC, douglara commented on app/views/layouts/internal.html.erb
> +        <aside class="w-60">
Tava dando uma olhada aqui na diferença entre o `aside` e `sidebar`
https://aastudio.fr/Sidebar-and-Aside-are-different.html

Pelo jeito o correto seria utilizar o sidebar, vou aplicar a mudança.

2023-09-26 21:38 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +        <aside class="w-60">
Interessante! Nesse caso o correto seria div msm

2023-09-26 21:42 UTC, douglara commented on app/views/layouts/internal.html.erb
> +          <nav class="h-20">
Então.. pelo flex para a sidebar e a navbar ficarem nos lugares corretos eu tive que separar elas
![image](https://github.com/douglara/woofed-crm/assets/14988496/208f6a40-cd11-49c0-8a85-ff368abe55d0)

Dei uma olhada no grid mas não acertei para simplificar
https://tailwindcss.com/docs/grid-row

2023-09-26 21:54 UTC, YukioArie commented on app/views/layouts/internal.html.erb
> +          <nav class="h-20">
Mas desse jeito tá legal tbm, no final das contas aquele arquivo .nav.html.erb vai deixar de exitir. Na verdade eu n vi necessidade de existir esse arquivo

2023-09-27 11:35 UTC, douglara commented on app/views/layouts/internal.html.erb
> +      <div class="flex h-full">
```suggestion
    <div id="app" class="h-screen">
      <div class="flex h-full">
```

2023-09-27 12:16 UTC, douglara commented on app/views/layouts/internal.html.erb
> +          <nav class="h-20">
Boaa blz fiz a remoação dele

2023-09-27 12:21 UTC, YukioArie approved these changes

2023-09-27 12:55 UTC, merged