Fixe configs
douglara/woofed-crm pull request #72
Opened 2023-09-27 10:32 UTC by douglara

2023-09-27 15:57 UTC, YukioArie requested changes

2023-09-27 15:57 UTC, YukioArie commented on config/tailwind.config.js
> +        '100': '1.313rem',
O tamanho do line height em 1.313rem é diferente que em 150% 
150% : 
![image](https://github.com/douglara/woofed-crm/assets/45243355/bfcfb816-936a-4173-b94f-51594b1ccc4f)

1.313rem: 
![image](https://github.com/douglara/woofed-crm/assets/45243355/ef385e13-2c17-4946-b572-3b46d02dad53)

O ideal seria deixar em porcentagem e renomear os lineheight de acordo com o valor deles, por exemplo: '150': '150%' 
![image](https://github.com/douglara/woofed-crm/assets/45243355/799814f0-0437-4051-a3f0-b81e08964248)

2023-09-28 11:17 UTC, douglara commented on config/tailwind.config.js
> +        '100': '1.313rem',
Boaa bem reparado

Acho que agora ficou correto

![image](https://github.com/douglara/woofed-crm/assets/14988496/1430c532-0151-45f8-8d63-155f57756237)


![image](https://github.com/douglara/woofed-crm/assets/14988496/d511d6cb-3d28-480c-810d-58a6271a70e0)

![image](https://github.com/douglara/woofed-crm/assets/14988496/69595405-6126-4304-ba39-ab933490a712)

2023-09-28 11:56 UTC, YukioArie commented on config/tailwind.config.js
> +        '100': '1.313rem',
Agora ficou show! 🚀

2023-09-28 11:56 UTC, YukioArie approved these changes

2023-09-28 11:59 UTC, merged