Convert pipeline to tailwind (#36)
douglara/woofed-crm pull request #77
Opened 2023-09-29 15:38 UTC by YukioArie

2023-09-29 15:39 UTC, YukioArie commented
Ref (#36)

2023-09-30 14:25 UTC, douglara commented
Alguns possíveis ajustes visuais: tamanhos, cores e espaçamento

![image](https://github.com/douglara/woofed-crm/assets/14988496/672fc406-4d6b-4a70-9671-e74ce1ce7c24)

2023-09-30 20:49 UTC, douglara requested changes

2023-09-30 20:49 UTC, douglara commented on app/views/accounts/pipelines/_stage.html.erb
> +    <div id="dropdownDotsHorizontal" class="z-10 hidden !w-48 !-left-16  bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
Aqui acho que é legal tirarmos os !important

2023-09-30 20:49 UTC, douglara commented on app/views/accounts/pipelines/_deal.html.erb
> +
```suggestion
```

2023-09-30 20:49 UTC, douglara commented on app/views/accounts/pipelines/_deal.html.erb
> +          <!-- <div class="bg-auxiliary-palette-red-down-2 border-auxiliary-palette-red-down text-auxiliary-palette-red"></div> -->
Boaas!

2023-09-30 21:03 UTC, douglara commented
Alguns detalhes de layout

![image](https://github.com/douglara/woofed-crm/assets/14988496/8514d0cd-361a-4bd3-9822-8744d7ae2eb3)

![image](https://github.com/douglara/woofed-crm/assets/14988496/0a20e4c6-e90a-43f0-be25-c40097c56db0)


![image](https://github.com/douglara/woofed-crm/assets/14988496/4a183eeb-505c-4b7a-a2ec-d363868b4938)

![image](https://github.com/douglara/woofed-crm/assets/14988496/4f5468c2-2db4-40bf-a0c4-636da5c010a6)


![image](https://github.com/douglara/woofed-crm/assets/14988496/13c5b99e-6830-4d93-9a60-7074d4b6f051)

2023-09-30 21:56 UTC, merged