Layout settings page
douglara/woofed-crm pull request #93
Opened 2023-10-02 17:15 UTC by YukioArie

2023-10-02 17:37 UTC, YukioArie commented
Ref (#63)

2023-10-04 11:43 UTC, douglara requested changes

2023-10-04 11:43 UTC, douglara commented on app/views/accounts/settings/custom_attributes_definitions/index.html.erb
> +
```suggestion
```

2023-10-04 11:43 UTC, douglara commented on app/views/accounts/settings/index.html.erb
> +
Aqui da pra remover essas coisas

2023-10-04 11:46 UTC, merged